<div class="intro">
<table>
<tbody><tr style="text-align:top;">
<td><h2>Democracy pen nong gamtatkhiat huna kipan ahi hi</h2>
<h3>Mycitizen.net pen Kawlgamsung leh gampua tungte a ding-a kibawl, man ngenlo a kimuhkhopna mun hi a, hihna peuhah kipanpih nading ahi hi.</h3>

<ul class="intro_list">
<li>Lunglutna leh haksatna kibatpih te tawh kimu ding</li>
<li>Kipawlna ah thahatzawk na ding</li>
<li>Sep leh bawl ding te geelkhawm ding</li>
<li>Na aw uh kiza sak ding</li>
<li>A thupi thulela kihawm ding</li>
<li>Na hamphatna uh leh hih theihna te zanghsiam ding</li>
<li>Internet haksatna munte ah kizopna ngah ding</li>
</ul>
<p><a href="/signup" target="_top" class="button">Minsazian bawlin</a> ahih keileh <a href="http://mycitizen.net/my:start" target="_blank">sinbehin</a>.</p>
<p class="intro_community">a kipawlkhopna adingin hih a kisam hiam? <a href="http://mycitizen.net/web:start" target="_blank">Kihel in</a>.
</p>
</td>
<td>
<div class="intro-video">
<h2>Watch our video:</h2>
    <iframe width="350" height="200" src="//www.youtube.com/embed/UkZDu58fLSE?rel=0&showinfo=0" frameborder="0" allowfullscreen=""></iframe>
</div>
</td>
</tr>
</tbody></table>
</div>