<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{var $robots => "noindex"}
{block title}{_"Page Not Found"}{/block}
{block content}

<div class="wrapper-text">
<h1>{_"Page Not Found"}</h1>

<img src="{$baseUri}/images/ma-lay-town.png" style="float:right;"/>

<h2><b class="icon-warning"></b>Error 404</h2>

<div style="font-size:1.2em; padding:20px 0; width:400px;">{_"The page you requested could not be found. Please correct the address, return to the previous page, or go back home."}</div>

<div style="font-size:1.1em; padding:20px 0;">
	<a href="javascript:window.history.back();" class="button" style="padding:5px 7px;"><b class="icon-list"></b>{_"back"}</a>
	<a href="/" class="button" style="padding:5px 7px;"><b class="icon-org"></b>{_"home"}</a>
</div>

</div>
{/block}