<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{layout none}
<!DOCTYPE html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<style>
        body { color: #333; background: white; width: 500px; margin: 100px auto }
        h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
        p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
        small { font-size: 70%; color: gray }
</style>

<h1>Server Error</h1>

<p>We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.</p>

<p>error 500</p>