<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Edit Group"}{/block}
@{block #content}
<div class="group_edit_updateform">

	{control updateform error}

{if !isset($image_too_large) && !isset($image_props_wrong)}
	<div class="back"><a href="{plink Group:default, $group_id}" title="{_"cancel and return"}" class="ajax"><b class="icon-cancel"></b></a></div>
<div class="edit-primary">
	<h2>{_"Basic Information"}</h2>
{/if}

{if isset($img_src) && $img_src!=null}
	<div class="group-edit-image{if !isset($image_too_large) && !isset($image_props_wrong)} edit-image-small{/if}">
		<h3>{_"Edit the group image"}</h3>
		<div class="images">
			<div class="image-full"><img src="data:{$mime_type};base64,{$img_src}" id="crop"/></div>
			<div class="icon-large"><p>Large icon:</p>{ifset $large_icon}{!$large_icon}{else}{_"Needs to be created."}{/if}</div>
			<div class="icon-small"><p>Small icon:</p>{ifset $icon}{!$icon}{else}{_"Needs to be created."}{/if}</div>
		</div>
		<div class="image-buttons">
		{if isset($image_too_large) ||  isset($image_props_wrong)}
			<div>{_"Click inside the image and select your avatar."}</div>
		{/if}

			<input type="submit" value="remove" onClick="removeGroupAvatar({$group_id});return false;" />
			<input type="hidden" id="x" name="x" />
			<input type="hidden" id="y" name="y" />
			<input type="hidden" id="w" name="w" />
			<input type="hidden" id="h" name="h" />
			<input type="hidden" id="factor" value="{$factor}" />
			<a href="javascript:void(0);" id="crop_button" onClick="doCrop(); return false;" class="button">{_"crop and resize"}</a>
		</div>
	</div>
{/if}

{if !isset($image_too_large) && !isset($image_props_wrong)}
	<div class="edit-wrapper" style="float:left;width:48%;">
		{control updateform}			
	</div>
<div class="cleaner"></div>
</div>
{/if}


{if !isset($image_too_large) && !isset($image_props_wrong)}
<div class="edit-secondary">
	<h2>{_"Additional Information"}</h2>
	<h4>{_"Below you can add details: Describe the topics of this group by one or more tags. If your group is located in a particular town, you can mark it on a map. These information will help other users to find your group."}</h4>

<table class="edit-secondary-table">
<tr>
{ifset $group_id}
<td class="edit-secondary-table-td">
	<div class="group-edit-map">
		<h3>{_"Edit the location"}</h3>
		{control mapedit}
	</div>
</td>
{/if}

<td class="edit-secondary-table-td">
		<h3>{_"Add or remove tags"}</h3><img src="{$baseUri}/images/help.png" class="help-icon" title="{_"Add the tags one by one."}" style="float:right;"/>
{/if}
	   {control tagform begin}
	
		{snippet tagHandle}
{if !isset($image_too_large) && !isset($image_props_wrong)}
		{ifset $group_id}
			<table id="rule_tail_container" class="newSelect">
			{ifset $group_tags}
			{foreach $group_tags as $key=>$tag_name}
				<tr>
					<td>
					{foreach $tag_name->getPath() as $tag}
						<span>{? echo _t_tags($tag)}</span>
					{if !$iterator->isLast()}
						<div class="tag-inner"></div>
					{/if}
					{/foreach}
					</td>
					<td><input type="submit" value="X" onClick="removeTag_Group({$group_id},{$key});return false;" /></td>
				</tr>	
			{/foreach}
			{/if}
			</table>
		{!$control['tagform']['add_tag']->control}
		{/if}
{/if}
		{/snippet}
		{control tagform end}
{if !isset($image_too_large) && !isset($image_props_wrong)}
</td>
</tr>
{ifset $group_id}
<tr>
	<td class="edit-secondary-table-td">
		<h3>{_"Manage members of this group"}</h3>
		{control groupmemberlister}
	</td>
	<td class="edit-secondary-table-td">
		<h3>{_"Manage subscribed resources"}</h3>
		{control unsubscriberesourceform}		
	</td>
</tr>
{/if}
</table>
	<div class="cleaner"></div>
</div>
{/if}

</div>
<script>
    jQuery(function($) {
        $('#crop').Jcrop({
        	minSize: [{!$min_size_x},{!$min_size_y}],
        	aspectRatio: 4/5,
        	onChange: enableCrop,
			onSelect: enableCrop
        });
    });
</script>
{/block}