<div class="intro">
<table>
<tbody><tr style="text-align:top;">
<td><h2>သင်လှုပ်ရှားတက်ကြွလာသည်နှင့်တပြိုင်နက်ဒီမိုကရေစီလည်းစတင်သည်။</h2>
<h3>Mycitizen.net သည် နိုင်ငံသားအချင်းချင်းထိစပ်ဆက်သွယ်နိုင်ရေးအတွက် ဒေသခံရပ်ရွာအသိုင်း အဝိုင်းတို့ အသုံးပြုနိုင်မည့် အခမဲ့စင်မြင့် တခုဖြစ်သည်။</h3>

<ul class="intro_list">
<li>ကြုံတွေ့နေရသောပြဿနာနှင့် စိတ်ပါ၀င်စားမှုနယ်ပယ်တူသည့်သူများကိုရှာဖွေနိုင်မည်</li>
<li>အုပ်စုအတွင်းပိုမိုအင်အားကောင်းလာစေမည်</li>
<li>လုပ်ဆောင်ရမည့်လှုပ်ရှားမှုများကို စုပေါင်းအစီအစဉ်ဆွဲနိုင်စေမည်</li>
<li>သင့်အသံကိုအများကြားသိစေနိုင်မည်</li>
<li>အရေးကြီးသောသတင်းများကိုဖလှယ်နိုင်မည်</li>
<li>သင့်အခွင့်အရေးကိုလုံခြံုစိတ်ချစွာကျင့်သုံးစေနိုင်မည်</li>
<li>အင်တာနက်နှေးသောနေရာ၌ပင်အသုံးဆက်သွယ်အသုံးပြုနိုင်မည်</li>
</ul>
<p><a href="/signup" target="_top" class="button">Sign up</a> or <a href="http://mycitizen.net/my:start" target="_blank">learn more</a>.</p>
<p class="intro_community">Need this for your own community? <a href="http://mycitizen.net/web:start" target="_blank">Get involved</a>.
</p>
</td>
<td>
<div class="intro-video">
<h2>Watch our video:</h2>
    <iframe width="350" height="200" src="//www.youtube.com/embed/UkZDu58fLSE?rel=0&showinfo=0" frameborder="0" allowfullscreen=""></iframe>
</div>
</td>
</tr>
</tbody></table>
</div>