<div class="intro">
<table>
<tbody><tr style="text-align:top;">
<td><h2>Zaukphung cu nangmah na cawlcangh tikah a thok</h2>
<h3>Mycitizen.Net cu ramchung le ramleng kawlram bupi mi hna nih khuaram kong khuakhannak ah a lak in hmankhawhmi hmunhma a si.</h3>

<ul class="intro_list">
<li>Nangmah he lungduh le harnak aa khatmi na hmuh khawh hna lai</li>
<li>A bu in thawn deuhnak</li>
<li>Hmunkhat ah riantuanti ding timhtuahnak</li>
<li>Na sining le authawng theihternak</li>
<li>A biapimi thawngpang le thil itheihternak</li>
<li>Nuhrin Covo na ngaihmi kha zalawngte in hmankhawhnak</li>
<li>Internet a thalonak hmuh zong ah fawite in pehtlaih khawhnak</li>
</ul>
<p><a href="/signup" target="_top" class="button">Athar sernak</a> asilole <a href="http://mycitizen.net/" target="_blank">Hngalh taaknak</a>.</p>
<p class="intro_community">Na mipi hna caah na herh ve maw? <a href="http://mycitizen.net/myzg:web:start" target="_blank">Hika in itel</a>.
</p>
</td>
<td>
<div class="intro-video">
<h2>Watch our video:</h2>
    <iframe width="350" height="200" src="//www.youtube.com/embed/lvKy_og2QhI?rel=0&showinfo=0" frameborder="0" allowfullscreen=""></iframe>
</div>
</td>
</tr>
</tbody></table>
</div>