<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<!DOCTYPE HTML>
<html>
	<head>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    	<meta name="description" content="{$PROJECT_DESCRIPTION}" />
    	<meta name="robots" content="{$robots}" n:ifset="$robots" />
    	<meta http-equiv="Content-Language" content="{$language_code}" />
		<link rel="shortcut icon" type="image" href="{$CDN}images/favicon.ico" />
    	<link rel="stylesheet" media="screen" href="{$CDN}css/mycitizen.min.css" />
		<link rel="stylesheet" media="screen" href="{$CDN}css/jquery.fancybox.min.css" />
{ifset $load_external_js_css}
		<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
		<link href='//fonts.googleapis.com/css?family=Open+Sans:800' rel='stylesheet' type='text/css'>
{else}
		<script type="text/javascript" src="{$CDN}js/jquery-1.10.2.min.js"></script>
		<link href='{$CDN}css/OpenSans/OpenSans.css' rel='stylesheet' type='text/css'>
{/if}

{ifset $load_external_js_css_deactivated}
		<link rel="stylesheet" href="//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.css">
		<script src="//cdn.jsdelivr.net/qtip2/2.2.0/jquery.qtip.min.js"></script>
{else}
		<link type="text/css" rel="stylesheet" href="{$CDN}css/jquery.qtip.min.css" />
		<script type="text/javascript" src="{$CDN}js/jquery.qtip.min.js"></script>
{/if}
		<script type="text/javascript" src="{$CDN}js/jquery.nette.js"></script>
		<script type="text/javascript" src="{$CDN}js/base-functions.min.js"></script>
		<script type="text/javascript" src="{$CDN}js/jquery.json-2.2.min.js"></script>
		<script type="text/javascript" src="{$CDN}js/jquery.fancybox.min.js"></script>
		<script type="text/javascript" src="{$CDN}js/jquery-ui-1.10.4.min.js"></script>
{ifset $load_js_css_zxcvbn}
	{ifset $load_external_js_css}
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/zxcvbn/1.0/zxcvbn-async.min.js"></script>
	{else}
		<script type="text/javascript" src="{$CDN}js/zxcvbn-async.js"></script>	
	{/if}
{/if}
{ifset $logged}
	{ifset $load_external_js_css}
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/gcal.js"></script>
		<link rel="stylesheet" media="screen" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" />
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.12/css/jquery.Jcrop.css" type="text/css" />
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.12/js/jquery.Jcrop.min.js"></script>	
	{else}
		<script type="text/javascript" src="{$CDN}js/fullcalendar.min.js"></script>
		<script type="text/javascript" src="{$CDN}js/gcal.js"></script>
		<link rel="stylesheet" media="screen" href="{$CDN}css/fullcalendar.css" />
		<script src="{$CDN}js/jquery.Jcrop.min.js"></script>
		<link rel="stylesheet" href="{$CDN}css/jquery.Jcrop.min.css" type="text/css" />
	{/if}
		<script type="text/javascript" src="{$CDN}js/tag-it.min.js"></script>
		<link rel="stylesheet" media="screen" href="{$CDN}css/jquery.tagit.css" />
		<link rel="stylesheet" media="screen" href="{$CDN}css/tagit.ui-zendesk.css" />
		<link rel="stylesheet" media="screen" href="{$CDN}css/jquery.tree.css" />
		<link rel="stylesheet" media="screen" href="{$CDN}css/jquery.calendarPicker.min.css" />
		<script src="{$CDN}js/ckeditor/ckeditor.js"></script>
		<script type="text/javascript" src="{$CDN}js/jquery.calendarPicker.min.js"></script>
		<script type="text/javascript" src="{$CDN}js/jquery.tree.min.js"></script>

{/if}

	<script>
    {* Functions that require Latte and must therefore remain in the template *}
	
		function loadActivity(where, id, latest) {
			$(where).animate({ opacity:0},function() {
				$(this).load("{!$baseUri_np}?do=activity&id="+id+"&latest="+latest,function() {
					$(this).animate({ opacity:1});
					$('.fancybox-inner').animate({
						scrollTop: $("#activity-scroll-target-"+id).offset().top - 90
					}, 2000);
				});
			});
		}

{ifset $logged}
		function doCrop() {
			var x = $('#x').val();
			var y = $('#y').val();
			var w = $('#w').val();
			var h = $('#h').val();
			var factor = $('#factor').val();
			if (w==0 || h==0) { alert({_"Please select first a part of the image."}); return false };
			window.location=this.location+'&do=crop&x='+x+'&y='+y+'&w='+w+'&h='+h+'&factor='+factor;	
		}
	
		function reloadMessages() {
			$.ajax({
					url:"{!$baseUri_np}?do=reloadStatusBar",
					dataType:"json"
				}).done(function(payload){
					$("#messages").html(payload['message_indicator']);
					$(document).attr("title", payload['title']+{$PROJECT_NAME}+" | {include #title}");				
			});
		}
		
	function PMPOPMoveToTrash(resource_id) {
		if(resource_id != null) {
			$.post("{!$baseUri}?do=moveToTrash&resource_id="+resource_id);
		}
	}
	
	function PMPOPMoveFromTrash(resource_id) {
		if(resource_id != null) {
			$.post("{!$baseUri}?do=moveFromTrash&resource_id="+resource_id);
		}
	}

	function PMPOPMarkRead(resource_id) {
		if(resource_id != null) {
			$.post("{!$baseUri}?do=markRead&resource_id="+resource_id);
		}
	}

	function PMPOPMarkUnread(resource_id) {
		if(resource_id != null) {
			$.post("{!$baseUri}?do=markUnread&resource_id="+resource_id);
		}
	}


    function enableCrop(c) {
    	$('#x').val(c.x);
		$('#y').val(c.y);
    	$('#w').val(c.w);
		$('#h').val(c.h);
    }
    
	$(document).ready(function() {
		$('.trash-radio').change(function(){
			$('#frmfilter-filter').click();
		});

		setInterval("reloadMessages()",60*1000);
		setInterval("onlineStatus()",65*1000);
		onlineStatus();
	});


	var status = {};
	var status_small = {};
	var status_title = {};
	var status_b = false;
	var status_small_b = false;
	var status_title_b = false;
	
	function onlineStatus() {
		$(".online-status").each(function(){
			var $element = $(this);
			var object_id = $(this).attr("object_id");
			status[object_id] = '';
			status_b=true;
		});
		$(".online-status-small").each(function(){
			var $element = $(this);
			var object_id = $(this).attr("object_id");
			status_small[object_id] = '';
			status_small_b=true;
		});
		$(".online-status-title").each(function(){
			var $element = $(this);
			var object_id = $(this).attr("object_id");
			status_title[object_id] = '';
			status_title_b=true
		});
		
		if (status_b) {
			$(".online-status").promise().done(function() {
				var json = JSON.stringify(status);
				$.ajax({
					url:"{!$baseUri_np}?do=onlineStatus&show_date=1",
					dataType:"json",
					data: {'data':json}
				}).done(function(status_output){
					for (var object_id in status_output) {
						$(".online-status[object_id="+object_id+"]").html(status_output[object_id]);
					}
				});
			});
		}
		if (status_small_b) {
			$(".online-status-small").promise().done(function(){
				var json = JSON.stringify(status_small);
				$.ajax({
					url:"{!$baseUri_np}?do=onlineStatus&show_date=0",
					dataType:"json",
					data: {'data':json}
				}).done(function(status_output){
					for (var object_id in status_output) {
						$(".online-status-small[object_id="+object_id+"]").html(status_output[object_id]);
					}
				});
			});
		}
		if (status_title_b) {
			$(".online-status-title").promise().done(function(){
				var json = JSON.stringify(status_title);
				$.ajax({
					url:"{!$baseUri_np}?do=onlineStatus&span=0",
					dataType:"json",
					data: {'data':json}
				}).done(function(status_output){
					for (var object_id in status_output) {
						var name = $(".online-status-title[object_id="+object_id+"]").attr("name");
						var newTitle = "<h4>" + name + "</h4>" + status_output[object_id];
						$(".online-status-title[object_id="+object_id+"]").qtip('option', 'content.text', newTitle);
					}
				});
			});
		}
	}
{/if}
	</script>
	<script type="text/javascript" src="//maps.google.com/maps/api/js?sensor=false&libraries=geometry"></script>
	<style>
	 .sortable-placeholder { height: 10px; line-height: 1.2em; background-color:#D0CCC3; width:430px; margin:10px; border-radius:5px;}
	 
@media print {
  #mobile_alert, #mobile_alert *, #topheader, #topheader *, .footer, .footer *, .resource-browser-actions, .resource-browser-filter {
    visibility: hidden;
    height:0;
  }
  
  .layout {
  	width: 100%;
  }
  
  .resource-browser-container {
  	position: absolute;
    left: 0;
    top: 0;
  }
  }
}
	</style>
	<title>{$PROJECT_NAME} | {include #title}</title>
</head>
<body>
<input id="baseUri" type="hidden" value="{!$baseUri}" />
{ifset $mobile}
	<div id="mobile_alert">
		<!-- mobile phone detected. -->
		<a href="https://mycitizen.net/download:mobile" class="button">{_"Download the mobile application"} <a href="javascript:void(0)" onclick="$('#mobile_alert').slideUp('normal'); createCookie('mycitizenNetMobileAlert', 'closed', 2);" style="float:right;">X</a>
	</div>
	<script>
	if (readCookie('mycitizenNetMobileAlert')=='closed') {
		$('#mobile_alert').hide();
	}
	</script>
{/if}

	<div id="layout">
		<div id="topheader">
			<div class="header">
				<div class="login" style="{ifset $logged}min-height:70px;{/if}min-width:170px;">
				{ifset $logged}
					<a href="{link User:default, $my_id}" class="user-info" title="{_"go to your profile"}">{!$image} {$username}</a>
					<div><a href="?toggleChat=toggle" target="_top" id="external_chat" title="{_"chat window"}"><img src="{!$CDN}images/new-window.png" style="float:right; padding-top:6px; cursor:pointer;"/></a>
				<script>
					$(document).ready(function(){
						if (top.location != location) {
							$('#external_chat').attr('href',location);
						}
					});
				</script>
						<a href="{link User:messages}" title="{_"read or write messages"}"><span id="messages">{!$messages}</span></a>
						<div class="hidden-menu" style="display:none; opacity:0.00;">
						<div class="fading">
							<a href="{link User:edit, $my_id}" class="button" >{_"Edit profile"}</a>
							<a href="#activity_box" class="button" id="show_activity">{_"Recent activity"}</a>

							<a href="{link User:logout}" class="button" >{_"Sign out"}</a>
						</div>
						</div>
					</div>
				<div id="activity_box" class="activity-box" style="display:none;">
					<h2>{_"Recent Activity"}</h2>
					<input id="latest_items" type="checkbox" name="latest_items"></input>
					<label for="latest_items">{_"Include all new users, groups and resources that you are allowed to view."}</label>
					<div id="load-more-1">
					</div>
				</div>
				{else}
				<div>
					<a href="{link User:login}" class="button" >{_"Sign in"}</a>
					<a href="{link User:register}" class="button" >{_"Sign up"}</a>
				</div>
				{/if}

			</div>

			</div> <!-- header -->

			<div class="logo">
				<h1><a href="{link Homepage:default}" class="ajax"><img src="{$CDN}images/logo.png" alt="{$PROJECT_NAME}" width="120" title="{_"Return to the home screen."}"/></a></h1>
			</div>
			<div class="language">
				<form>
					<select name="language" id="language_select" onChange="selectLanguage(this.value);">
					{foreach Language::getArray() as $lang_id=>$lang_name}
						{var $flag=> Language::getFlag($lang_id)}
						<option value="{$lang_id}" {if $flag == $language}selected="selected"{/if}>{$lang_name}</option>
					{/foreach}
					</select>
				</form>
			</div>
		
			<div class="main_menu">
			{snippet mainMenu}
				{control menu}
			{/snippet}
			</div> <!-- main menu -->

			<div class="messages">
				{control messages}
			</div> <!-- messages -->
			
		</div> <!-- topheader -->

		<div class="content" style="margin-top:30px;">
{snippet mainContent}
	@{include #content}
<div id="progressbar" class="progressbar" style="display:none;"/></div>
<script>
{* These scripts need to relad with the mainContent snippet. *}
	$(document).ready(function(){
		$('[title!=""]').qtip('destroy');
		$('[title!=""]').qtip({
			style: { classes: 'qtip-light qtip-rounded qtip-shadow' },
			show: { delay: 800 },
			position: {
        		my: 'top left',
		        at: 'bottom right',
		        target: 'mouse',
		        adjust: {
                	x: 15,
                	y: 5
            	}
			}
		});
		
		$('form input[type=submit]').click(function(){
        	$(this).attr("clicked", "true");
	    });
	});
</script>
{/snippet}
			<div class="cleaner"></div>
		</div>

{snippet popupchat}
{ifset $logged}
{ifset $popup_chat}
	{include $popup_chat}
{/if}
{/if}
{/snippet}

		<div class="footer">
			{include $footer}

			<div class="rules-and-conditions">
				{_"By using this platform you accept our Terms of Use and our Privacy policy."}
				<ul>
				<li><a href="{$TC_URL}" target="_blank">{_"Terms of Use"}</a></li>
				<li><a href="{$PP_URL}" target="_blank">{_"Privacy policy"}</a></li>
				</ul>
			</div>			
			<div class="software-info">
				<a href="https://www.mycitizen.net" target="_blank">mycitizen.net</a> {_"is a product of"} <a href="http://www.burma-center.org" target="_blank">Burma Center Prague</a> - <a href="http://mycitizen.net/about:license">{_"license"}</a>. <a href="http://www.ecn.cz" target="_blank">webdesign, css - econnect</a>.
				<div class="cleaner"></div>
				<h4>Stay Connected</h4>
				<a href="https://www.facebook.com/mycitizen.net" target="_blank"><img src="{$CDN}/images/facebook_icon.png" style="height:16px; width:16px;float:left;padding:0 5px;"/></a>
				<a href="https://twitter.com/mycitizennet" target="_blank"><img src="{$CDN}/images/twitter_icon.png" style="height:16px; width:16px;float:left;padding:0 5px;"/></a>
			</div>
			<div class="sponsor-credits">
				<a href="http://www.mzv.cz/jnp/en/foreign_relations/human_rights/transition_promotion_program/index.html" target="_blank"><img src="{$CDN}/images/transition-200px.gif" class="logo_sponsor" alt="logo of sponsor" style="float:right;"/></a>This project is supported from the resources of the Ministry of Foreign Affairs of the Czech Republic within its Transition Promotion Program.
			</div>
			<div class="cleaner"></div>
		</div> <!-- footer -->
		
	</div> <!-- layout -->


{ifset $piwik_url_bare}
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  // you can set up to 5 custom variables for each visitor
  _paq.push(["setCustomVariable", 1, "language", {$language_code}, "visit"]);
  _paq.push(["setCustomVariable", 2, "access_level", "{ifset $access_level}{!$access_level}{else}0{/if}", "visit"]);
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "{!$piwik_url_bare}";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", {$PIWIK_ID}]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
{/if}
	</body>
</html>