<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<!DOCTYPE HTML>
<html>
	<head>
    	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    	<meta name="description" content="{$PROJECT_DESCRIPTION}" />
    	<meta name="robots" content="{$robots}" n:ifset="$robots" />
    	<meta http-equiv="Content-Language" content="{$language_code}" />
		<link rel="shortcut icon" type="image" href="{$baseUri}images/favicon.ico" />

    	<link rel="stylesheet" media="screen" href="{$baseUri}css/mycitizen.min.css" />
		<link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.fancybox.min.css" />
	
{ifset $load_js_css_tree}
		<link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.tree.css" />
{/if}
{ifset $load_js_css_datetimepicker}
		<link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.calendarPicker.min.css" />
{/if}
		<link type="text/css" rel="stylesheet" href="{$baseUri}css/jquery.qtip.min.css" />
{ifset $load_js_css_jcrop}
{ifset $load_external_js_css}
		<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.12/css/jquery.Jcrop.css" type="text/css" />
{else}
		<link rel="stylesheet" href="{$baseUri}css/jquery.Jcrop.min.css" type="text/css" />
{/if}
{/if}
{ifset $load_external_js_css}
		<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
		<link href='//fonts.googleapis.com/css?family=Open+Sans:800' rel='stylesheet' type='text/css'>
{else}
		<script type="text/javascript" src="{$baseUri}js/jquery-1.10.2.min.js"></script>
		<link href='{$baseUri}css/OpenSans/OpenSans.css' rel='stylesheet' type='text/css'>
{/if}
		<script type="text/javascript" src="{$baseUri}js/jquery.nette.js"></script>
		<script type="text/javascript" src="{$baseUri}js/base-functions.min.js"></script>
		<script type="text/javascript" src="{$baseUri}js/jquery.json-2.2.min.js"></script>
		<script type="text/javascript" src="{$baseUri}js/jquery.fancybox.min.js"></script>
{ifset $load_js_css_zxcvbn}
	{ifset $load_external_js_css}
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/zxcvbn/1.0/zxcvbn-async.min.js"></script>
	{else}
		<script type="text/javascript" src="{$baseUri}js/zxcvbn-async.js"></script>	
	{/if}
{/if}

		<script type="text/javascript" src="{$baseUri}js/jquery-ui-1.10.4.custom.min.js"></script>
		<link rel="stylesheet" media="screen" href="{$baseUri}css/jquery-ui-1.10.4.custom.min.css" />
{ifset $load_fullcalendar}
	{ifset $load_external_js_css}
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.min.js"></script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/gcal.js"></script>
		<link rel="stylesheet" media="screen" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/1.6.4/fullcalendar.css" />		
	{else}
		<script type="text/javascript" src="{$baseUri}js/fullcalendar.min.js"></script>
		<script type="text/javascript" src="{$baseUri}js/gcal.js"></script>
		<link rel="stylesheet" media="screen" href="{$baseUri}css/fullcalendar.css" />		
	{/if}
{/if}
		
{ifset $load_js_css_editor}
		<script src="{$baseUri}js/ckeditor/ckeditor.js"></script>
{/if}

{ifset $load_js_css_jcrop}
{ifset $load_external_js_css}
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.12/js/jquery.Jcrop.min.js"></script>
{else}
<script src="{$baseUri}js/jquery.Jcrop.min.js"></script>
{/if}
<script>
    function enableCrop(c) {
    	$('#x').val(c.x);
		$('#y').val(c.y);
    	$('#w').val(c.w);
		$('#h').val(c.h);
    }
    
    function doCrop() {
    	var x = $('#x').val();
    	var y = $('#y').val();
    	var w = $('#w').val();
    	var h = $('#h').val();
    	var factor = $('#factor').val();
    	if (w==0 || h==0) { alert({_"Please select first a part of the image."}); return false };
		window.location=this.location+'&do=crop&x='+x+'&y='+y+'&w='+w+'&h='+h+'&factor='+factor;	
    }
</script>
{/if}

<script>
	$(document).ready(function(){
		$("a.active").prop("href", "javascript:void(0);");
		$("a.active").css("cursor", "default");
		
		$('[title!=""]').qtip({
			style: { classes: 'qtip-light qtip-rounded qtip-shadow' },
			show: { delay: 800 },
			position: {
        		my: 'top left',
		        at: 'bottom right',// {$tooltip_position},
		        target: 'mouse',
		        adjust: {
                	x: 15,
                	y: 5
            	}
			}
		});
	});


	$(document).ready(function() {
		$(".tags-fancybox").fancybox({
			closeBtn : true,
			leftRatio: 0.15,
			topRatio: 0,
			maxWidth: 500,
			helpers : {
				overlay : {
					css: {'background' : 'rgba(200, 200, 200, .5)'}
				},
				title : null
			},
		});
	});
	
	$(document).ready(function() {
		$(".fancybox").fancybox({
			closeBtn : true,
			helpers : {
				overlay : {
					css: {'background' : 'rgba(200, 200, 200, .5)'}
				},
				title : null
			},
		});
	});
	
	function loadActivity(where, id, latest) {
		$(where).animate({ opacity:0},function() {
			$(this).load("{!$baseUri}?do=activity&id="+id+"&latest="+latest,function() {
				$(this).animate({ opacity:1});
				$('.fancybox-inner').animate({
					scrollTop: $("#activity-scroll-target-"+id).offset().top - 90
				}, 2000);
			});
		});
	}

{ifset $logged}
	$(document).ready(function() {
		$('.trash-radio').change(function(){
			$('#frmfilter-filter').click();
		});
	});
	
	$(document).ready(function() {
		setInterval("reloadMessages()",60*1000);
		setInterval("onlineStatus()",65*1000);
		onlineStatus();
	});
	
	function reloadMessages() {
		$.ajax({
				url:"{!$baseUri}?do=reloadStatusBar",
				dataType:"json"
			}).done(function(payload){
				$("#messages").html(payload['message_indicator']);
				$(document).attr("title", payload['title']+{$PROJECT_NAME}+" | {include #title}");				
		});
	}

	var status = {};
	var status_small = {};
	var status_title = {};
	var status_b = false;
	var status_small_b = false;
	var status_title_b = false;
	
	function onlineStatus() {
		$(".online-status").each(function(){
			var $element = $(this);
			var object_id = $(this).attr("object_id");
			status[object_id] = '';
			status_b=true;
		});
		$(".online-status-small").each(function(){
			var $element = $(this);
			var object_id = $(this).attr("object_id");
			status_small[object_id] = '';
			status_small_b=true;
		});
		$(".online-status-title").each(function(){
			var $element = $(this);
			var object_id = $(this).attr("object_id");
			status_title[object_id] = '';
			status_title_b=true
		});
		
		if (status_b) {
			$(".online-status").promise().done(function() {
				var json = JSON.stringify(status);
				$.ajax({
					url:"{!$baseUri}?do=onlineStatus&show_date=1",
					dataType:"json",
					data: {'data':json}
				}).done(function(status_output){
					for (var object_id in status_output) {
						$(".online-status[object_id="+object_id+"]").html(status_output[object_id]);
					}
				});
			});
		}
		if (status_small_b) {
			$(".online-status-small").promise().done(function(){
				var json = JSON.stringify(status_small);
				$.ajax({
					url:"{!$baseUri}?do=onlineStatus&show_date=0",
					dataType:"json",
					data: {'data':json}
				}).done(function(status_output){
					for (var object_id in status_output) {
						$(".online-status-small[object_id="+object_id+"]").html(status_output[object_id]);
					}
				});
			});
		}
		if (status_title_b) {
			$(".online-status-title").promise().done(function(){
				var json = JSON.stringify(status_title);
				$.ajax({
					url:"{!$baseUri}?do=onlineStatus&span=0",
					dataType:"json",
					data: {'data':json}
				}).done(function(status_output){
					for (var object_id in status_output) {
						var name = $(".online-status-title[object_id="+object_id+"]").attr("name");
						var newTitle = "<h4>" + name + "</h4>" + status_output[object_id];
						$(".online-status-title[object_id="+object_id+"]").qtip('option', 'content.text', newTitle);
					}
				});
			});
		}
	}
{/if}

</script>
<title>{$PROJECT_NAME} | {include #title}</title>
</head>
<body>
{ifset $mobile}
	<div id="mobile_alert">
		<!-- mobile phone detected. -->
		<a href="https://mycitizen.net/download:mobile" class="button">{_"Download the mobile application"} <a href="javascript:void(0)" onclick="$('#mobile_alert').slideUp('normal'); createCookie('mycitizenNetMobileAlert', 'closed', 2);" style="float:right;">X</a>
	</div>
	<script>
	if (readCookie('mycitizenNetMobileAlert')=='closed') {
		$('#mobile_alert').hide();
	}
	</script>
{/if}

	<div id="layout">
		<div id="topheader">
			<div class="header">
				<div class="login" style="{ifset $logged}min-height:70px;{/if}min-width:170px;">
				{ifset $logged}
					<a href="{link User:default, $my_id}" class="user-info" title="{_"go to your profile"}">{!$image} {$username}</a>
					<div>
						<a href="{link User:messages}" title="{_"read or write messages"}"><span id="messages">{!$messages}</span></a>
						<div class="hidden-menu" style="display:none; opacity:0.00;">
						<div class="fading">
							<a href="{link User:edit, $my_id}"  class="button" >{_"Edit profile"}</a>
{if !isset($homepage) || !$homepage}
							<a href="#activity_box" class="button" id="show_activity">{_"Recent activity"}</a>
<script type="text/javascript">
$(function() {
	$("#show_activity").fancybox({
		minWidth:800,
		minHeight:500,
		closeBtn : true,
		helpers : {
			overlay : {
				css: {'background' : 'rgba(200, 200, 200, .5)'}
			},
			title : null
		},
		afterLoad: function() {
			var latest = $("input[name='latest_items']").prop('checked')?'1':'0';
			loadActivity("#load-more-1", 2, latest);
		}
	});
});
$(document).ready(function(){
	$("input[name='latest_items']").change(function(){
		var latest = $(this).prop('checked')?'1':'0';
		loadActivity("#load-more-1", 2, latest);
	});
});
</script>
{/if}
							<a href="{link User:logout}" class="button" >{_"Sign out"}</a>
						</div>
						</div>
					</div>
				<div id="activity_box" class="activity-box" style="display:none;">
					<h2>{_"Recent Activity"}</h2>
					<input id="latest_items" type="checkbox" name="latest_items"></input>
					<label for="latest_items">{_"Include all new users, groups and resources that you are allowed to view."}</label>
					<div id="load-more-1">
					</div>
				</div>
			{else}
				<div>
					<a href="{link User:login}" class="button" >{_"Sign in"}</a>
					<a href="{link User:register}" class="button" >{_"Sign up"}</a>
				</div>
			{/if}

			</div>

			</div> <!-- header -->
<script>
	$(document).ready(function(){
		$('.user-info').mouseenter(function(){
			$('.hidden-menu').filter(":hidden").slideDown("normal", function(){ //fade
        		$(this).fadeTo("normal", 1.00, function() { //slide up
         		});
     		});
		});
	
		$('.header').mouseleave(function(){
			$('.hidden-menu').filter(":visible").fadeTo("normal", 0.00, function(){ //fade
        		$(this).slideUp("normal", function() { //slide up
         		});
     		});
     		$(this).clearQueue();
		});
	});
</script>
			<div class="logo">
				<h1><a href="{link Homepage:default}"><img src="{$baseUri}images/logo.png" alt="{$PROJECT_NAME}" width="120" title="{_"Return to the home screen."}"/></a></h1>
			</div>
			<div class="language">
				<form>
					<select name="language" id="language_select" onChange="selectLanguage(this.value);">
					{foreach Language::getArray() as $lang_id=>$lang_name}
						{var $flag=> Language::getFlag($lang_id)}
						<option value="{$lang_id}" {if $flag == $language}selected="selected"{/if}>{$lang_name}</option>
					{/foreach}
					</select>
				</form>
			</div>
		
			<div class="main_menu">
				{control menu}
			</div> <!-- main menu -->

			<div class="messages">
				{control messages}
			</div> <!-- messages -->
			
		</div> <!-- topheader -->

		<div class="content" style="margin-top:30px;">
			@{include #content}
			<div class="cleaner"></div>
		</div>

		<div class="footer">
			{include $footer}

			<div class="rules-and-conditions">
			{? $terms_link = '<a href='.$TC_URL.' target="_blank">'._t("Terms of Use").'</a>'}
			{? $pp_link = '<a href='.$PP_URL.' target="_blank">'._t("Privacy policy").'</a>'}
				{!_"By using this platform you accept our %s and our %s.", $terms_link, $pp_link}
			</div>			
			<div class="software-info">
				<a href="https://www.mycitizen.net" target="_blank">mycitizen.net</a> {_"is a product of"} <a href="http://www.burma-center.org" target="_blank">Burma Center Prague</a> - <a href="http://mycitizen.net/about:license">{_"license"}</a>. <a href="http://www.ecn.cz" target="_blank">webdesign, css - econnect</a>.
				<div class="cleaner"></div>
				<h4>Stay Connected</h4>
				<a href="https://www.facebook.com/mycitizen.net" target="_blank"><img src="{$baseUri}/images/facebook_icon.png" style="height:16px; width:16px;float:left;padding:0 5px;"/></a>
				<a href="https://twitter.com/mycitizennet" target="_blank"><img src="{$baseUri}/images/twitter_icon.png" style="height:16px; width:16px;float:left;padding:0 5px;"/></a>
			</div>
			<div class="sponsor-credits">
				<a href="http://www.mzv.cz/jnp/en/foreign_relations/human_rights/transition_promotion_program/index.html" target="_blank"><img src="{$baseUri}/images/transition-200px.gif" class="logo_sponsor" alt="logo of sponsor" style="float:right;"/></a>This project is supported from the resources of the Ministry of Foreign Affairs of the Czech Republic within its Transition Promotion Program.
			</div>
			<div class="cleaner"></div>
		</div> <!-- footer -->
		
	</div> <!-- layout -->

	<script type="text/javascript" src="{$baseUri}js/jquery.qtip.min.js"></script>
{ifset $load_js_css_datetimepicker}
	<script type="text/javascript" src="{$baseUri}js/jquery.calendarPicker.min.js"></script>
{/if}
{ifset $load_js_css_tree}
	<script type="text/javascript" src="{$baseUri}js/jquery.tree.min.js"></script>
{/if}

{ifset $piwik_url_bare}
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  // you can set up to 5 custom variables for each visitor
  _paq.push(["setCustomVariable", 1, "language", {$language_code}, "visit"]);
  _paq.push(["setCustomVariable", 2, "access_level", "{ifset $access_level}{!$access_level}{else}0{/if}", "visit"]);
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "{!$piwik_url_bare}";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", {$PIWIK_ID}]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
{/if}
	</body>
</html>