<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<!DOCTYPE HTML>
<html>
<head>
	<link rel="stylesheet" media="screen" href="{$baseUri}css/mycitizen.min.css" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{_"Image Browser"}</title>
	<link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.fancybox.min.css" />
{ifset $load_external_js_css}
	<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
	<link href='//fonts.googleapis.com/css?family=Open+Sans:800' rel='stylesheet' type='text/css'>
{else}
	<script type="text/javascript" src="{$baseUri}js/jquery-1.10.2.min.js"></script>
	<link href='/css/OpenSans/OpenSans.css' rel='stylesheet' type='text/css'>
{/if}
	<script type="text/javascript" src="{$baseUri}js/jquery.fancybox.min.js"></script>
	<script>
		function insert(url) {
			var message = '';
			window.opener.CKEDITOR.tools.callFunction({$CKEditorFuncNum}, url, message);
			window.close();
		}
		function deleteImage(fileName) {
			if (confirm({_"Do you really want to delete this file?"}+" "+fileName)) {
				$.getJSON('{!$baseUri}?do=deleteImage&file_name=' + encodeURIComponent(fileName) + '&user_id={!$user_id}',function(payload){
					location.href=self.location.href;
				});
			}
		}
	</script>
</head>
<body>
<div id="layout">
	<div id="topheader">
		<div style="padding:20px 20px 0 250px;">
			<h1>{_"Please select an image"}</h1>
			<h2>{_"Images of %s", $user_name}</h2>
		</div>
		<div style="float:right;">
			<a href="javascript:void(0);" onclick="window.close()" class="button" style="text-decoration:none;">{_"close"}</a>
		</div>
	</div>
	<div id="content">
	<div class="wrapper-text">
		<p>{_"If you need to upload a new image, close this window and click on 'Upload'."}<br/>
		<b>{_"Note:"}</b> {_"Images are public. If you want to prevent others from seeing them, you should choose a file name that is hard to guess."}</p>
	<table>
		<tr>
{var $row => 1}
{var $column => 1}

{if isset($data) && count($data)}
{foreach $data as $item}
		<td style="width:150px; border:solid 1px #CCC; padding:10px 2px 5px 10px; margin:0; border-radius: 8px; background-color:#eae9e3;">
		<div style="height:120px;">
			<div style="float:right; cursor:pointer;">
				<b onclick="deleteImage({$item['file_name']});" class="icon-cancel" title="{_"delete"}"></b>
			</div>
			<a href="{$item['web_path']}" class="image-fancybox" rel="group" title="{$item['file_name']}, {$item['width']}x{$item['height']}"><img src="data:image/jpeg;base64,{!$item['img_b64']}" style="border:solid 1px #666;"/></a>
		</div>
		<a href="javascript:void(0);" onclick="insert({$item['web_path']})" class="button" style="text-decoration:none;">{_"insert"}</a>
		<h4>{$item['file_name']}</h4>
		<h4>{$item['width']} x {$item['height']} {_"pixel"}</h4>
		</td>
		{? $column++}
		{if $column > 6}
			{? $column = 1}
			{? $row++}
		</tr><tr>
		{/if}
{/foreach}
{else}
	<h3>{_"No images."}</h3>
{/if}
		</tr>
	</table>
	</div>
	</div>
</div>
<script>
$(document).ready(function() {
	$("a.image-fancybox").fancybox();
});
</script>
</body>
</html>