<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<!DOCTYPE HTML>
<html>
<head>
	<link rel="stylesheet" media="screen" href="{$CDN}css/mycitizen.min.css" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>{_"File Browser"}</title>
	<link rel="stylesheet" media="screen" href="{$CDN}css/jquery.fancybox.min.css" />
{ifset $load_external_js_css}
	<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
	<link href='//fonts.googleapis.com/css?family=Open+Sans:800' rel='stylesheet' type='text/css'>
{else}
	<script type="text/javascript" src="{$CDN}js/jquery-1.10.2.min.js"></script>
	<link href='{$CDN}css/OpenSans/OpenSans.css' rel='stylesheet' type='text/css'>
{/if}
	<script type="text/javascript" src="{$CDN}js/jquery.fancybox.min.js"></script>
	<script>
		function insert(url) {
			var message = '';
			window.opener.CKEDITOR.tools.callFunction({$CKEditorFuncNum}, url, message);
			window.close();
		}
		function deleteFile(fileName) {
			if (confirm({_"Do you really want to delete this file?"}+" "+fileName)) {
				$.getJSON('{!$baseUri}?do=deleteFile&file_name=' + encodeURIComponent(fileName) + '&user_id={!$user_id}',function(payload){
					location.href=self.location.href;
				});
			}
		}
		function renameFile(fileName) {
			var newName = prompt({_"Please enter the new file name:"}, fileName);
			if (newName != null && newName != fileName) {
				$.getJSON('{!$baseUri}?do=renameFile&old_name=' + encodeURIComponent(fileName) + '&new_name=' + encodeURIComponent(newName) + '&user_id={!$user_id}',function(payload){
					if (payload != 'true') {
						alert(payload);
					} else {
						location.href=self.location.href;
					}
				});
			}
		}

	</script>
</head>
<body>
<div id="layout">
	<div id="topheader">
		<div style="padding:20px 20px 0 250px;">
			<h1>{_"Please select a file"}</h1>
			{ifset $user_name}<h2>{_"Files of %s", $user_name}</h2>{/if}
		</div>
		<div style="float:right;">
			<a href="javascript:void(0);" onclick="window.close()" class="button" style="text-decoration:none;">{_"close"}</a>
		</div>
	</div>
	<div id="content">
	<div class="wrapper-text">
		<p>{_"If you need to upload a new file, close this window and click on 'Upload'."}<br/>
		<b>{_"Note:"}</b> {_"These files are public. If you want to prevent others from seeing them, you should choose a file name that is hard to guess."}</p>
	<table>
		<tr>
{var $row => 1}
{var $column => 1}

{if isset($data) && count($data)}
{foreach $data as $item}
		<td style="width:190px; border:solid 1px #CCC; padding:10px 2px 5px 10px; margin:0; border-radius: 8px; background-color:#eae9e3; vertical-align:top;">
			<div style="float:right; cursor:pointer;">
				<b onclick='deleteFile({$item['file_name']});' class="icon-cancel" title="{_"delete"}"></b>
			</div>
		<table style="width:110px;">
		<tr><td style="height:120px; vertical-align:top;">
			<div{if !isset($item['width'])} style="text-align:center;padding-top:20px;"{/if}>
			{ifset $item['width']}<a href="{$item['web_path']}" class="image-fancybox" rel="group" title="{$item['file_name']}, {$item['width']}x{$item['height']}"><img src="data:image/jpeg;base64,{!$item['img_b64']}" style="border:solid 1px #666;"/></a>
			{else}
			<img src="{!$item['src']}"/>
			{/if}
			</div>
		</td></td>
		<tr><td>
		<a href="javascript:void(0);" onclick="insert({$item['web_path']})" class="button" style="text-decoration:none;">{_"insert"}</a>
		</td></td>
		<tr><td style="height:2.5em; vertical-align:top; cursor:pointer;" onclick='renameFile({$item['file_name']});' title='{_"click to rename"}'>
		<h4>{$item['file_name']}</h4>
		</td></td>
		<tr><td style="height:1.5em; vertical-align:top;">
		{ifset $item['width']}
		{$item['width']} x {$item['height']} {_"pixel"}
		{else}
		{/if}
		</td></td>
		<tr><td style="height:1.5em; vertical-align:top;">
		{ifset $item['modified_date']}
		{$item['modified_date']}
		{/if}
		</td></tr>
		</table>
		</td>
		{? $column++}
		{if $column > 6}
			{? $column = 1}
			{? $row++}
		</tr><tr>
		{/if}
{/foreach}
{else}
	<h3>{_"No files."}</h3>
{/if}
		</tr>
	</table>
	</div>
	</div>
</div>
<script>
$(document).ready(function() {
	$("a.image-fancybox").fancybox();
});
</script>
</body>
</html>