<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.2.2 beta
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="description" content="{$PROJECT_DESCRIPTION}">
      <meta name="robots" content="{$robots}" n:ifset="$robots">
    
      <link rel="stylesheet" media="screen" href="{$baseUri}css/styles.css" />
      <link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.fancybox.css" />
      <link rel="stylesheet" media="screen" href="{$baseUri}css/jquery.tree.css" />
      <script type="text/javascript" src="{$baseUri}js/jquery-1.4.3.min.js"></script>
      <script type="text/javascript" src="{$baseUri}js/jquery.nette.js"></script>
      <script type="text/javascript" src="{$baseUri}js/jquery.fancybox.js"></script>
      <script type="text/javascript" src="{$baseUri}js/base-functions.js"></script>
      <script type="text/javascript" src="{$baseUri}js/jquery.tree.js"></script>
      <script type="text/javascript" src="{$baseUri}js/jquery.json-2.2.js"></script>
      <link rel="shortcut icon" type="image" href="{$baseUri}images/favicon.ico" />  
      <title>Users</title>
   </head>
   <body>

	@{control $type:body}
</body>
</html>

