<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.2 beta
 *
 * @author http://mycitizen.org
 *
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}Resource - Register{/block}
{block content}
		<script>

      $(document).ready(function(){
         $("#frmupdateform-event_timestamp").datetimepicker({
	timeFormat: 'hh:mm tt z',
	showTimezone: true
});
      });
   </script>

		{control updateform error}
		{control updateform}
{/block}
