<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Create Resource"}{/block}
{block content}
<script>
	$(document).ready(function(){
		$("#frmupdateform-event_timestamp").hide();
		var divToday = $("<span>").attr('id', 'today').html({_"now"}).addClass("button").css('margin', '2px');
	    var divDate = $("<div>").attr('id', 'date').css('width', '500px');
	    
	    $("#frmupdateform-event_timestamp").parent().append(divToday).append(divDate);
	    	
		 var calendarPicker = $("#date").calendarPicker({
			monthNames:[{_'Jan'}, {_'Feb'}, {_'Mar'}, {_'Apr'}, {_'May'}, {_'Jun'}, {_'Jul'}, {_'Aug'}, {_'Sep'}, {_'Oct'}, {_'Nov'}, {_'Dec'}],
			dayNames: [{_'Sun'}, {_'Mon'}, {_'Tue'}, {_'Wed'}, {_'Thu'}, {_'Fri'}, {_'Sat'}],
			//useWheel:true,
			//callbackDelay:500,
			years:2,
			months:4,
			days:5,
			hours:4,
			minutes:2,
			showDayArrows:false,
			callback:function(cal) {
			  $("#frmupdateform-event_timestamp").val(cal.currentDate);
			}});
			
		$("#today").click(function(){
			calendarPicker.changeDate(new Date())
		});
	});
</script>
		{control updateform error}
		{control updateform}
{/block}
