<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Details of the resource"} {$data['resource_name']}{/block}
{block content}

<div class="back">
	{if isset($_SERVER['HTTP_REFERER']) && preg_match('/messages/',$_SERVER['HTTP_REFERER'])}
	<a href="{link User:messages}" title="{_"Back to the list of messages"}" class="list"><b class="icon-list"></b></a>
	{elseif isset($_SERVER['HTTP_REFERER']) && preg_match('/reports/',$_SERVER['HTTP_REFERER'])}
	<a href="{link Administration:reports}" title="{_"Back to the list of reports"}" class="list"><b class="icon-list"></b></a>
	{else}
	<a href="{link Resource:default}" title="{_"Back to the list of resources"}" class="list"><b class="icon-list"></b></a>
	{/if}
</div>

<div class="about">

	<div class="icons">
	{ifset $logged_user}
		{ifset $default_data['object_data']['logged_user_member']}
		<div class="subscription-status-detail">
			<b {if $default_data['object_data']['logged_user_member'] == 1}class="icon-subscriber" title="{_"I am subscribed."}">{else}class="icon-no-subscriber" title="{_"I am not subscribed."}">{/if}</b>
		</div>
		{/if}
	{/if}
		
		<div class="icon-visibility">
		{if $data['resource_visibility_level'] == 1}
			<b class="icon-world"  title="{_"visible to the world"}"></b>
		{elseif $data['resource_visibility_level'] == 2}
			<b class="icon-registered" title="{_"only visible to registered users"}"></b>
		{else}
			{ifset $iamowner}
			<b class="icon-person" title="{_"only visible to you"}"></b>
			{else}
			<b class="icon-person" title="{_"only visible to subscribers"}"></b>
			{/if}
		{/if}
		</div>

	</div>

	<b class="main-icon icon-{$resource_type}" title="{$resource_type_label}"></b>
		
	<h4>{_"Last activity: "}{$last_activity|date:'j.n.Y'}</h4>

	<h2>
	{ifset $default_data}
		{if Auth::ADMINISTRATOR == Auth::isAuthorized(3,$default_data['object_data']["resource_id"])}
			<a href="{link Resource:edit, $default_data['object_data']["resource_id"]}"><b class="icon-resource-edit" title="{_"edit"}"></b></a>
		{else}
			{ifset $logged_user}	
			<a  href="#report_form" id="report_box"><b class="icon-warning" title="{_"Report resource"}"></b></a>
			{/if}
		{/if}
	{/if}
	{$data['resource_name']}
	</h2>
	
	{ifset $logged_user}
	<div id="report_form" style="display:none;">
		<h4>{_"Here you can report the resource if you think it has violated the rules. Reports will be processed by our moderators."}</h4>
		{control reportform}
	</div>

	<script type="text/javascript">
	$(function() {
		$("#report_box").fancybox({
			closeBtn : true,
			helpers : {
				overlay : {
					css: {'background' : 'rgba(200, 200, 200, .5)'}
				},
				title : null
			},
		});
	});
	</script>
	{/if}
	
	<div class="resource-detail-description">
	
		{$data['resource_description']}

		<div class="resource-detail-language">	
			<h3>{_"Language"}:</h3>
			{$object_language}
		</div>

		<div class="resource-detail-tags">
			<h3>{_"Topics"}</h3>
			{if isset($resource_tags) && count($resource_tags)}
			<table>
				{?$i=0}
				 {foreach $resource_tags as $key=>$tag_name}
					<tr>
						<td><div onmouseover="$('#tag_{$i}').show();" onmouseout="$('#tag_{$i}').hide();" class="tag-outer" style="white-space:nowrap; overflow:hidden;text-overflow:ellipsis;width:200px;">
							{foreach $tag_name->getIdWithPath() as $tag}
								{if $iterator->isLast()}
									<a href="?do=searchtag&tag_id={$tag['id']}"><b class="icon-tag"></b>{? echo _t_tags($tag['name'])}</a>
								{else}
									<span id="tag_{$i}" class="tag-hidden" style="display:none;margin-right:3px;color:#f05a28;"><a href="?do=searchtag&tag_id={$tag['id']}"><b class="icon-tag"></b>{? echo _t_tags($tag['name'])}</a> <div class="tag-inner" style="width=0;height:0;border-left: 5px solid #BCB6AA;border-top: 5px solid transparent; border-bottom: 5px solid transparent;display:inline-block;"></div></span>
								{/if}
							{/foreach}
							</div>
						</td>
					</tr>
				{?$i++}
				{/foreach}
			</table>
			{else}
			{_"No tags"}
			{/if}
		</div>
		
	</div>

	{ifset $iamowner}
	<div class="resource-owner">
		{_"This is my resource."}
	</div>
	{else}
		{ifset $owner}
		{if 0 < Auth::isAuthorized(1,$owner["owner_id"])}
	<div class="resource-owner">
		<a href="{link User:default, $owner['owner_id']}" title="{_"View resource owner:"} {$owner['owner_name']}">{_"Resource owner: "} {? echo User::getImage($owner['owner_id'], 'icon')}</a>
	</div>
		{/if}
		{/if}
	{/if}

	{ifset $logged_user}
	<div class="resource-actions">
	{ifset $default_data}
		{ifset $default_data['object_data']['logged_user_member']}
		{if $default_data['object_data']['logged_user_member'] == 0}
		<div>
			<a href="javascript:void(0);" onClick='userInsert_Resource({$logged_user},{$default_data['object_data']["resource_id"]},{link Resource:default, $default_data['object_data']["resource_id"]});' class="button">{_"Subscribe"}</a>
		</div>
		{/if}
		{if $default_data['object_data']['logged_user_member'] == 1}
		<div>
			<a href="javascript:void(0);" onClick='userRemove_Resource({$logged_user},{$default_data['object_data']["resource_id"]},{link Resource:default, $default_data['object_data']["resource_id"]});' class="button">{_"Cancel subscription"}</a>
		</div>
		{/if}
		<div class="group-subscriptions">
			<span id="subscribe_as_group_header" style="cursor:pointer;" class="button">{_"Subscribe as group"}</span>
			<div id="subscribe_as_group_body" style="display:none;">
				<p>{_"Select one or more groups to subscribe to this resource. Only groups are displayed that you own or where you have at least moderator permissions."}</p>					
				{control subscriberesourceform}
			</div>
			<script>
			$(document).ready(function(){
				$('#subscribe_as_group_header').click(function(){
					$('#subscribe_as_group_body').slideToggle(500);
				});
			});
			</script>
		</div>
	{/if}
	</div>
	{/if}
 {/if}
	

	{ifset $showmap}
	<div class="resource-detail-map">
		<h3>{_"Resource location on a map"}</h3>
		{control map}
	</div>
	{/if}

	{ifset $default_data}
	{if Auth::ADMINISTRATOR == Auth::isAuthorized(3,$default_data['object_data']['resource_id'])}
	<div class="administration">
	<h3>{_"Administration"}</h3>
	{control resourceadministrator begin}
		<label>{_"Enabled"}</label>{$control['resourceadministrator']['status']->control}
		{$control['resourceadministrator']['send']->control}
	{control resourceadministrator end}
	</div>
	{/if}
	{/if}

</div>

<div class="detail-right">
	<div class="resource-detail-extended">
		{if $data['resource_type'] == 1}
			{$data['message_text']}
			{ifset $data['message_type']}
				{if $data['message_type'] == 2}
					<a href="{link User:default,$data['resource_author']}">{_"See details about the user and respond to the request."}</a>
				{/if}
			{/ifset}
		{/if}
		{if $data['resource_type'] == 2 && $data['event_url'] != ""}
		<div class="resource-link">
			{ifset $screenshot}<h2>{_('Screenshot')}</h2>{!$screenshot}{/if}
			<a href="{$data['event_url']}" target="_blank" class="button"><b class="icon-www"></b>{_"Go to resource"}</a>
		</div>
		{/if}
		{if $data['resource_type'] == 3 && $data['organization_url'] != ""}
		<div class="resource-link">
			{ifset $screenshot}<h2>{_('Screenshot')}</h2>{!$screenshot}{/if}
			<a href="{$data['organization_url']}" target="_blank" class="button"><b class="icon-www"></b>{_"Go to resource"}</a>
		</div>
		{/if}
		{if $data['resource_type'] == 4 && $data['text_information_url'] != ""}
		<div class="resource-link">
			{ifset $screenshot}<h2>{_('Screenshot')}</h2>{!$screenshot}{/if}
			<a href="{$data['text_information_url']}" target="_blank" class="button"><b class="icon-www"></b>{_"Go to resource"}</a>
		</div>
		{/if}
		{if $data['resource_type'] == 6 && $data['other_url'] != ""}
		<div class="resource-link">
			{ifset $screenshot}<h2>{_('Screenshot')}</h2>{!$screenshot}{/if}
			<a href="{$data['other_url']}" target="_blank" class="button"><b class="icon-www"></b>{_"Go to resource"}</a>
		</div>
		{/if}
		{if $data['resource_type'] == 4}
		<div class="resource-text">
			<h2>{_('Information')}</h2>
			{!$data['text_information']|htmlpurify}
		</div>
		{/if}
		{if $data['resource_type'] == 3}
		<div class="resource-text">
			<h2>{_('Information')}</h2>
			{!$data['organization_information']|htmlpurify}
		</div>
		{/if}
		{if $data['resource_type'] == 2}

		<div class="resource-event-time resource-detail-connections" style="padding:20px 30px; margin:20px 0;">
			{ifset $event_alert}<img src="/images/clock-alert.png" style="float:right;" title="{_"The event is upcoming."}"/>
			{elseifset $event_ahead}<img src="/images/clock-ahead.png" style="float:right;" title="{_"The event is in the future."}"/>
			{else}<img src="/images/clock.png" style="float:right;" title="{_"The event is over."}"/>{/if}
			<h2>{_"Event Details"}</h2>
			<table>
			<tr>
			{if $data['event_timestamp']==$data['event_timestamp_end']}
			<td><h3>{_"Time:"}</h3></td><td>{$start_formatted}</td>
			{else}
			<td><h3>{_"Start:"}</h3></td><td>{$start_formatted}</td>
			</tr><tr>
			<td><h3>{_"End:"}</h3></td><td>{$end_formatted}</td>
			{/if}
			</tr>
			{if isset($data['event_allday']) && $data['event_allday']}
			<tr>
			<td colspan="2"><h3>{_"All-day event"}</h3></td>
			</tr>
			{/if}
			{if isset($data['event_alert']) && $data['event_alert']}
			<tr>
			<td><h3>{_"Alarm:"}</h3></td><td>{$event_alert_times[$data['event_alert']]}</td>
			</tr>
			{/if}
			</table>
		</div>
		
		<div class="resource-text-event">
			<h2>{_('Information')}</h2>
			{!$data['event_description']|htmlpurify}
		</div>

		{/if}
		{if $data['resource_type'] == 7}
			<div class="report-text">
				{$data['report_text']}
			</div>
		{/if}

		{if $data['resource_type'] == 5}
		{if $data['media_type'] == 'media_youtube'}
			<div id="player"></div>

			<script>
			  // 2. This code loads the IFrame Player API code asynchronously.
			  var tag = document.createElement('script');
			  tag.src = "//www.youtube.com/iframe_api";
			  var firstScriptTag = document.getElementsByTagName('script')[0];
			  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

			  // 3. This function creates an <iframe> (and YouTube player)
			  //    after the API code downloads.
			  var player;
			  function onYouTubeIframeAPIReady() {
				player = new YT.Player('player', {
				  height: '390',
				  width: '640',
				  videoId: '{!$data['youtube_link']}',
				  modestbranding: '1',
				  autoplay: '0',
				  rel: '0',
				  events: {
					'onReady': onPlayerReady,
					'onStateChange': onPlayerStateChange
				  }
				});
			  }

			  // 4. The API will call this function when the video player is ready.
			  function onPlayerReady(event) {
				event.target.pauseVideo();
			  }

			  // 5. The API calls this function when the player's state changes.
			  //    The function indicates that when playing a video (state=1),
			  //    the player should play for six seconds and then stop.
			  var done = false;
			  function onPlayerStateChange(event) {
	//				if (event.data == YT.PlayerState.PLAYING && !done) {
	//				  setTimeout(stopVideo, 6000);
	//				  done = true;
	//				}
			  }
			  function stopVideo() {
				player.stopVideo();
			  }
			</script>
		{/if}
		{if $data['media_type'] == 'media_vimeo'}
			<iframe src="http://player.vimeo.com/video/{$data['vimeo_link']}?portrait=0&color=333" width="640" height="480" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
		{/if}
		{if $data['media_type'] == 'media_bambuser'}
			<iframe src="http://embed.bambuser.com/broadcast/{$data['bambuser_link']}" width="640" height="480" frameborder="0">Your browser does not support iframes.</iframe>
		{/if}
		{if $data['media_type'] == 'media_soundcloud'}
			<script src="http://w.soundcloud.com/player/api.js" type="text/javascript"></script>
			<iframe width="640" height="200" scrolling="no" frameborder="no" src="http://w.soundcloud.com/player/?url=www.soundcloud.com/{$data['soundcloud_link']}&show_artwork=true"></iframe>
		{/if}

		{/if}
	</div>

	<div class="cleaner"></div>

	<div class="resource-detail-connections">
		<div class="resource_detail_members">
		{ifset $default_data}
			<h2>{_"Subscribed Users"}</h2>
			{if Auth::isAuthorized(3,$default_data['object_data']['resource_id'])>0 }
				{control detailresourcememberlister:body}
			{else}
				<p>{_"You are not allowed to see the subscribed users."}</p>
			{/if}
		{/if}
		</div>
 
		<div class="resource_detail_groups">
		{ifset $default_data}
			<h2>{_"Subscribed Groups"}</h2>
			{if Auth::isAuthorized(3,$default_data['object_data']['resource_id'])>0 }
				{control detailresourcegrouplister:body}
			{else}
				<p>{_"You are not allowed to see the subscribed groups."}</p>
			{/if}
		{/if}
		</div>
		<div class="cleaner"></div>
	</div>

	<div class="resource-detail-chatlist">
		{if $data['resource_type'] == 1}
			<h2>{_"Replies"}</h2>
		{else}
			<h2>{_"Comments"}</h2>
		{/if}
	{ifset $logged_user}
		{ifset $default_data}
		{ifset $default_data['object_data']['logged_user_member']}
			<div class="resource-detail-chatform">
			{if $default_data['object_data']['logged_user_member'] == 1}
				{if $data['resource_type'] == 1}
					<h4>{_"Post reply"}</h4>
				{else}
					<h4>{_"Post new comment"}</h4>
				{/if}
			  {control chatform}
			{else}
				{_"You need to subscribe in order to comment."}
			{/if}
			</div>
		{/if}
		{/if}
	{/if}

	{* Resource Comments *}		
	{ifset $logged_user}
		<h3>{_"Search Comments"}</h3>
		<div class="filter-body-chat">
			<div class="filter-block">
				<input type="text" class="text" name="name" id="search_name" value="" onkeyup="textChanged();" placeholder="{_"Filter by name"}"/>
				<a href="javascript:void(0);" id="clear_button" class="button" name="clear" >{_"Clear"}</a>
			</div>
		</div>
		{control chatlisterresource}
		
	<script>
		$(document).ready(function() {

			$('#clear_button').click(function(){
				$('#search_name').val('');
				showAll();
			});
		});
		
		var text='';
		var search='';
		
		function textChanged() {
			search = $('#search_name').val();
			if (search == text) {
				return false;
			}
			search = search.trim();
			filter();
			text = search;
		}
		
		$.extend($.expr[":"], {
			"containsNC": function(elem, i, match, array) {
				return (elem.textContent || elem.innerText || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
			}
		});

		function showAll() {
			$('.chat-author').parent().parent().parent().slideDown('slow');
		}
		
		function filter() {
			if (search.length<text.length) {
				$('.chat-author').parent().parent().parent().slideDown();
				$('.chat-author:not(:containsNC('+search+'))').parent().parent().parent().slideUp('normal');
			}
			else if (search!='') {
				$('.chat-author:not(:containsNC('+search+'))').parent().parent().parent().slideUp('fast');
			}
		}

	</script>
	{else}
		{_"Comments are only visible when you are signed in."}
	{/if}
	</div>
<script>
	$(document).ready(function() {
		CKEDITOR.replace( 'message_text', {
			height: '200px',
			width: '740px',
			filebrowserUploadUrl: '/?do=upload',
			filebrowserBrowseUrl: '/widget/browse/',
			allowedContent: 'p blockquote strong em; a[!href]; del ins; ul ol li; img(left,right)[!src,alt,width,height]',
			toolbarGroups: [
				{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
				{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ]},
				{ name: 'links'},
				{ name: 'insert'},
				{ name: 'styles'},
				{ name: 'colors'}
			],
			extraPlugins: 'smiley'
		});
	});
</script>
</div>
{/block}
