<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.2.1 beta
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_'Update Resource'}{/block}
@{block #content}
<script>
	$(document).ready(function(){
		$("#frmupdateform-event_timestamp").hide();
		var divToday = $("<span>").attr('id', 'today').html({_'now'}).addClass("button").css('margin', '2px');
	    var divDate = $("<div>").attr('id', 'date').css('width', '500px');
	    var dateSet = new Date($("#frmupdateform-event_timestamp").val());
	    if (dateSet == "Invalid Date") dateSet = 0;
	    
	    $("#frmupdateform-event_timestamp").parent().append(divToday).append(divDate);
	    	
		 var calendarPicker = $("#date").calendarPicker({
			monthNames:[{_'Jan'}, {_'Feb'}, {_'Mar'}, {_'Apr'}, {_'May'}, {_'Jun'}, {_'Jul'}, {_'Aug'}, {_'Sep'}, {_'Oct'}, {_'Nov'}, {_'Dec'}],
			dayNames: [{_'Sun'}, {_'Mon'}, {_'Tue'}, {_'Wed'}, {_'Thu'}, {_'Fri'}, {_'Sat'}],
			years:2,
			months:4,
			days:5,
			hours:4,
			minutes:2,
			showDayArrows:false,
			date:dateSet,
			callback:function(cal) {
			  $("#frmupdateform-event_timestamp").val(cal.currentDate);
			}});
			
		$("#today").click(function(){
			calendarPicker.changeDate(new Date())
		});
	});
</script>


<div class="resource_edit_updateform">

	<div class="back"><a href="{plink Resource:default, $resource_id}" title="{_'cancel and return'}"><b class="icon-cancel"></b></a></div>

	
		<div class="edit-wrapper" style="display:inline;width:60%;">
		{control updateform error}
	{control updateform}

<script>
{* set style directly in ResourcePresenter.php ! *}
	$(document).ready(function(){
		$('#frm-updateform').css({'display':'inline'});
	});
</script>




		{ifset $resource_id}
		<div class="resource-edit-map" style="display:inline;">
			<h4>{_'Edit the location'}</h4>
			{control mapedit}
		</div>
		{/if}
	
		<div class="cleaner"></div>
	
		<h3>{_'Below you can add details: Describe the topics of this resource by one or more tags. If you have created resource accessible only to selected peaople, you can insert recipients of this resource. These information will help other users to find your resource.'}</h3>
		<div class="resource-edit-tagform">
		<h3>{_'Add or remove tags'} </h3>
		<p><img src="/images/help.png" class="help-icon" title="{_'Add the tags one by one.'}" style="margin-bottom:-8px;"/></p>

	   {control tagform begin}
	
		{snippet tagHandle}
		{ifset $resource_id}
			<table id="rule_tail_container" class="newSelect">
			{ifset $resource_tags}
			{foreach $resource_tags as $key=>$tag_name}
				<tr>
					<td>
					{foreach $tag_name->getPath() as $tag}
						<span>{? echo StaticModel::pgettext('tags',$tag)}</span>
						{if !$iterator->isLast()}
						<div class="tag-inner" style="width=0;height:0;border-left: 5px solid #BCB6AA;border-top: 5px solid transparent; border-bottom: 5px solid transparent;display:inline-block;"></div>
						{/if}
				   {/foreach}
					</td>
					<td><input type="submit" value="X" onClick="removeTag_Resource({$resource_id},{$key});return false;" /></td>
				</tr>	
			{/foreach}
			{/if}
			</table>
		{!$control['tagform']['add_tag']->control}
		{/if}
	   {/snippet}
		{control tagform end}

<script>
	$(document).ready(function(){
		$('a#tag_select_button').addClass('button');
	});
</script>

		</div>
		
{ifset $resource_id}
	<div class="group-edit-membersform">
		<h3>{_'Manage subscribers of this resource'}</h3>
		{control resourcesubscriberlister}
	</div>

{/if}
{ifset $screenshot_url}
	<div class="group-edit-screenshot" style="width:33%;float:left;">
	<h3>{_('Screenshot')}</h3>
	{ifset $screenshot}{!$screenshot}{/if}
	</div>
{ifset $screenshot}	
<script>
	$(document).ready(function(){
		var src = $("#screenshot").attr("newsrc");
		var d = new Date();
		if ((typeof src != 'undefined') && (src != '')) {
			setTimeout(function(){
				var img = new Image();
				img.onload = function() {
					$("#screenshot").hide();
					$("#screenshot").attr("src", src+"?"+d.getTime());
					$("#screenshot").show();
				};
				img.onerror = function() {
					setTimeout(function(){
						$("#screenshot").hide();
						$("#screenshot").attr("src", src+"?"+d.getTime());
						$("#screenshot").show();					
					},15000);
 				};
 				img.src = src;
			},2000);
		}
	});
</script>
{/if}
{/if}

		</div>

	<div class="cleaner"></div>
</div>	
{/block}
