<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Edit Resource"}{/block}
@{block #content}
<script>
	$(document).ready(function(){
		$("#frmupdateform-event_timestamp").hide();
		$("#frmupdateform-event_timestamp_end").hide();
		var divToday1 = $("<span>").attr('id', 'today_1').html({_"now"}).addClass("button").css('margin', '2px');
{ifset $initial_selection}
		var divPreset = $("<span>").attr('id', 'preset').html({_"reset to initial selection"}).addClass("button").css('margin', '2px');
{else}
	var divPreset = '';
{/if}
	    var divDate1 = $("<div>").attr('id', 'date_1').css('width', '500px');
		var divToday2 = $("<span>").attr('id', 'today_2').html({_"now"}).addClass("button").css('margin', '2px');
	    var divDate2 = $("<div>").attr('id', 'date_2').css('width', '500px');
	    
	    if ($("#frmupdateform-event_timestamp").val() != 'undefined') {
	    	$("#frmupdateform-event_timestamp").parent().append(divToday1).append(divPreset).append(divDate1);
	    } else {
		    $("#frmupdateform-event_timestamp").parent().append(divToday1).append(divDate1);
		}
	    $("#frmupdateform-event_timestamp_end").parent().append(divToday2).append(divDate2);
	    	
		 var calendarPicker1 = $("#date_1").calendarPicker({
			monthNames:[{_'Jan'}, {_'Feb'}, {_'Mar'}, {_'Apr'}, {_'May'}, {_'Jun'}, {_'Jul'}, {_'Aug'}, {_'Sep'}, {_'Oct'}, {_'Nov'}, {_'Dec'}],
			dayNames: [{_'Sun'}, {_'Mon'}, {_'Tue'}, {_'Wed'}, {_'Thu'}, {_'Fri'}, {_'Sat'}],
			//useWheel:true,
			//callbackDelay:500,
			years:2,
			months:4,
			days:5,
			hours:4,
			minutes:2,
			showDayArrows:false,
			callback:function(cal) {
			  		$("#frmupdateform-event_timestamp").val(cal.currentDate);
			}});

		 var calendarPicker2 = $("#date_2").calendarPicker({
			monthNames:[{_'Jan'}, {_'Feb'}, {_'Mar'}, {_'Apr'}, {_'May'}, {_'Jun'}, {_'Jul'}, {_'Aug'}, {_'Sep'}, {_'Oct'}, {_'Nov'}, {_'Dec'}],
			dayNames: [{_'Sun'}, {_'Mon'}, {_'Tue'}, {_'Wed'}, {_'Thu'}, {_'Fri'}, {_'Sat'}],
			//useWheel:true,
			//callbackDelay:500,
			years:2,
			months:4,
			days:5,
			hours:4,
			minutes:2,
			showDayArrows:false,
			callback:function(cal) {
		  			$("#frmupdateform-event_timestamp_end").val(cal.currentDate);
			}});

		if ($("#frmupdateform-event_timestamp").val() != '') {
			var dateString = $("#frmupdateform-event_timestamp").val();
			calendarPicker1.changeDate(new Date(dateString))
		}

		if ($("#frmupdateform-event_timestamp_end").val() != '') {
			var dateString = $("#frmupdateform-event_timestamp_end").val();
			calendarPicker2.changeDate(new Date(dateString))
		}

		$("#today_1").click(function(){
			calendarPicker1.changeDate(new Date())
		});
		$("#today_2").click(function(){
			calendarPicker2.changeDate(new Date())
		});
		
		$("#preset").click(function(){
			var presetTime = $("#frmupdateform-preset_time").val();
			$("#frmupdateform-event_timestamp").val(presetTime);
			calendarPicker1.changeDate(new Date(presetTime));
		});

	});
</script>


<div class="resource_edit_updateform">

	<div class="back"><a href="{plink Resource:default, $resource_id}" title="{_'cancel and return'}"><b class="icon-cancel"></b></a></div>
<div class="edit-primary">
	<h2>{_"Basic Information"}</h2>
	
		{control updateform error}
	{control updateform}

<script>
{* @todo set style directly in ResourcePresenter.php ! *}
	$(document).ready(function(){
		$('#frm-updateform').css({'display':'inline'});
	});
</script>
	
	<div class="cleaner"></div>
</div>

<div class="edit-secondary">
	<h2>{_"Additional Information"}</h2>
	<h3>{_'Below you can add details: Describe the topics of this resource by one or more tags. These information will help other users to find your resource.'}</h3>

<table class="edit-secondary-table">
<tr>
	{ifset $resource_id}
	<td class="edit-secondary-table-td">
		<div class="resource-edit-map" style="display:inline;">
			<h4>{_'Edit the location'}</h4>
			{control mapedit}
		</div>
	</td>
	{/if}

	<td class="edit-secondary-table-td">
		<h3>{_'Add or remove tags'}</h3><img src="{$baseUri}/images/help.png" class="help-icon" title="{_"Add the tags one by one."}" style="float:right;"/>

	   {control tagform begin}
		{snippet tagHandle}
		{ifset $resource_id}
			<table id="rule_tail_container" class="newSelect">
			{ifset $resource_tags}
			{foreach $resource_tags as $key=>$tag_name}
				<tr>
					<td>
					{foreach $tag_name->getPath() as $tag}
						<span>{? echo _t_tags($tag)}</span>
						{if !$iterator->isLast()}
						<div class="tag-inner" style="width=0;height:0;border-left: 5px solid #BCB6AA;border-top: 5px solid transparent; border-bottom: 5px solid transparent;display:inline-block;"></div>
						{/if}
				   {/foreach}
					</td>
					<td><input type="submit" value="X" onClick="removeTag_Resource({$resource_id},{$key});return false;" /></td>
				</tr>	
			{/foreach}
			{/if}
			</table>
		{!$control['tagform']['add_tag']->control}
		{/if}
	   {/snippet}
		{control tagform end}
	</td>
	
<script>
	$(document).ready(function(){
		$('a#tag_select_button').addClass('button');
	});
</script>
</tr>
<tr>	
{ifset $resource_id}
	<td class="edit-secondary-table-td">
		<h3>{_'Manage subscribers of this resource'}</h3>
		{control resourcesubscriberlister}
	</td>
{/if}
{ifset $screenshot_url}
	<td class="edit-secondary-table-td">
	<h3>{_('Screenshot')}</h3>
	{ifset $screenshot}{!$screenshot}{/if}
	{ifset $resource_id}
	<a href="?do=removescreenshot&resource_id={!$resource_id}" class="button">{_"remove screenshot"}</a>
	{/if}
	</td>
{ifset $screenshot}	
<script>
	$(document).ready(function(){
		var src = $("#screenshot").attr("newsrc");
		var d = new Date();
		if ((typeof src != 'undefined') && (src != '')) {
			setTimeout(function(){
				var img = new Image();
				img.onload = function() {
					$("#screenshot").hide();
					$("#screenshot").attr("src", src+"?"+d.getTime());
					$("#screenshot").show();
				};
				img.onerror = function() {
					setTimeout(function(){
						$("#screenshot").hide();
						$("#screenshot").attr("src", src+"?"+d.getTime());
						$("#screenshot").show();					
					},15000);
 				};
 				img.src = src;
			},2000);
		}
	});
</script>
{/if}
{/if}
</tr>
</table>
	<div class="cleaner"></div>
</div>

<script>
	$(document).ready(function() {
		CKEDITOR.replace( 'organization_information', {
			height: '300px',
			width: '800px',
			filebrowserUploadUrl: '{!$baseUri}?do=upload',
			filebrowserBrowseUrl: '{!$baseUri}widget/browse/',
		});
		CKEDITOR.replace( 'event_description', {
			height: '300px',
			width: '800px',
			filebrowserUploadUrl: '{!$baseUri}?do=upload',
			filebrowserBrowseUrl: '{!$baseUri}widget/browse/',
		});
		CKEDITOR.replace( 'text_information', {
			height: '300px',
			width: '800px',
			filebrowserUploadUrl: '{!$baseUri}?do=upload',
			filebrowserBrowseUrl: '{!$baseUri}widget/browse/',
		});
		
		if ($("#frmupdateform-event_allday").prop('checked')) {
			$(".calHour").hide();
			$(".calMinute").hide();
		}
			
		$("#frmupdateform-event_allday").click(function(){
			if ($(this).prop('checked')) {
				$(".calHour").hide();
				$(".calMinute").hide();
			} else {
				$(".calHour").show();
				$(".calMinute").show();			}
		});

		if ($("#frmupdateform-event_timestamp").val() != $("#frmupdateform-event_timestamp_end").val()) {
			$("#frmupdateform-event_end").prop('checked', true);
			$("#frmupdateform-event_timestamp_end").parent().parent().show();
		} else {
			$("#frmupdateform-event_timestamp_end").parent().parent().hide();
		}
		
		$("#frmupdateform-event_end").click(function(){
			if ($(this).prop('checked')) {
				$("#frmupdateform-event_timestamp_end").parent().parent().show();
			} else {
				$("#frmupdateform-event_timestamp_end").parent().parent().hide();
			}
		});
	});
</script>
</div>	
{/block}
