<div>                                                                 
  <a id="tag_select_button" href="#tag_select_div">add new tag</a>
  <input id="tag_select_hidden" type="hidden" name="{$name}" value="{$control->getValue()}" />
</div>

<script type="text/javascript">
  $(document).ready( function(){
    $("#tag_tree_select").treeview();
    $("a#tag_select_button").fancybox({});
    $("div.tree a").on('click', function(){ 
      $(".active").removeClass("active");
      $(this).addClass("active");
    });
  });
</script>


<div style="display: none;">
  <div id="tag_select_div" style="width: 400px;float:center;">
    
    <div class="first_level">
      <h2 class="h2-line"><?=_('Select a tag')?></h2>
      <p><?=_('Select a tag that describes one of your interests and click add.')?></p>
    </div>
    <div class="tree" style="padding: 20px 50px;float:left;">
		<span class="folder-main ">&nbsp;</span>
        <span class="tree-main{if 0==$control->getValue()} active{/if}"><?=_('Tags')?></span>

      {var $current_level => 0}  
      <ul id="tag_tree_select" class="filetree" style="text-align:left;">
		
      {foreach $tree_array as $node}
      	{if $current_level < $node['level']}
  	  			<ul>
  	  			{var current_level => $node['level']}
      	{/if}
      	{while $current_level > $node['level']}
  	  			</ul></li>
  	 			{var current_level => $current_level-1}
      	{/while}
  	 
      	<li{if !in_array($node['tag_id'], $active_node_path)} class="closed"{/if}>
      		<span class="folder {=NString::webalize($object_type_name_array[$node['tag_id']])}">&nbsp;</span>
  	 			<span {if $node['tag_id']==$control->getValue()}class="active"{/if}>
  	 			<a href="#" onclick="
  	   			document.getElementById('tag_select_hidden').value='{!$node['tag_id']}';
  	   			return false;">
  					{$node['tag_name']}
  	 			</a>
  	 			</span>
  
      {/foreach}
      </ul>
      
    </div>  

	 <div class="confirm">
	   <a href="#" class="button-blue button" style="float: right;"onclick="addNewTag_User({$container_id},document.getElementById('tag_select_hidden').value);$.fancybox.close();return false;"><?=_('Add')?></a>
	 </div>
  </div>
</div>
