{* DEPRECATED! Listing the comments on resource pages *}

<div class="lister-header">
</div>

<div class="lister-body">
{snippet list_body}

<table>
    <tr>
        <th>
        </th>
        <th>
        </th>
        <th>
        </th>
    </tr>
	{foreach $data as $row}

		{var r_data => Resource::create($row['id'])->getResourceData()}
		{var r_author => User::create($r_data['resource_author'])->getUserData()}
        <tr>
			<td class="message_time" colspan=3>
				{* $r_data['time'] localize format*} 12.6.2013, 10:38:52
			</td>
        </tr>
		<td class="chat-author-avatar">
			<a href="{plink User:default, $r_data['resource_author']}" title="{$r_author['user_name']}">
			<img width="20" src="/scaled/?id={$r_data['resource_author']}&w=20&h=25" />
			</a>
		</td>
		<td class="chat-author">
			<a href="{plink User:default, $r_data['resource_author']}" title="{$r_author['user_name']}">
			{$r_author['user_login']}
			</a>
		</td>
		<tr>
			<td class="message-text" style="padding-left:10px;">
            	{!$r_data['message_text']|htmlpurify}
            </td>
		</tr>
    {/foreach}
</table> 
{/snippet}
</div>
<div class="lister-footer">
	{snippet list_pager}
	
	<div class="pager">
	{if $max_page > 1}
		<a href="{link changePage, page => 1}" class="pager-start{if $currentpage == 1} active{/if}">1</a>
	{/if}

	{if $max_page > 5}
	{if $currentpage > 4}
		<a href="{link changePage, page => $currentpage - 1}" class="pager-minus"><</a>
	{/if}
	{/if}

	{if $max_page > 2}
	{if $max_page < 6}
	{for $i = 2; $i <= $max_page-1; $i++}
		<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
	{/for}   
	{else}
	{if $currentpage <= 4}
	{? if ($currentpage+2 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
	{for $i = 2; $i <= $end; $i++}
		<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
	{/for}
	{else}
	{? if ($currentpage+3 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
	{for $i = $currentpage-2; $i <= $end; $i++}
		<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
	{/for}
	{/if}
	{/if}
	{/if}

	{if $max_page > 5}
	{if ($currentpage + 3) < $max_page}
		<a href="{link changePage, page => $currentpage + 1}" class="pager-plus">></a>
	{/if}
	{/if}

	{if $max_page > 1}
		<a href="{link changePage, page => $max_page}" class="pager-end{if $currentpage == $max_page} active{/if}">{$max_page}</a>
	{/if}
	</div>

	{/snippet}
</div>
