{* USED????????? *}
@{include #listerhead}
<div class="lister-header">

</div>
<div class="lister-body">
	{snippet list_body}
	@{include #listcontent}
	{/snippet}
</div>
<div class="lister-footer">
	{snippet list_pager}
	<a href="javascript:void(0);" onClick="pager({ifset $object_type}{!$object_type}{else}0{/if},{ifset $object_id}{!$object_id}{else}0{/if},'{!$name}',1);">|<<</a>
	{if $currentpage <= 1}
		<a href="{link changePage, page => 1}"><<</a>
	{else}
		<a href="{link changePage, page => $currentpage - 1}"><<</a>
	{/if}
	{for $i = $start; $i <= $end; $i++}
		<a href="{link changePage, page => $i}">{$i}</a>
	{/for}

	{if ($currentpage + 1) > $max_page}
		<a href="{link changePage, page => $max_page}">>></a>
	{else}
		<a href="{link changePage, page => $currentpage + 1}">>></a>
	{/if}
	<a href="{link changePage, page => $max_page}">>>|</a>
	{/snippet}
</div>
@{include #listertail}
