<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<div class="lister-header">
	{if isset($template_variables['map_used']) && $template_variables['map_used']}
		<img src="{$baseUri}images/map-circle-active.png" title="{_"Searched around your location."}" style="float:right;padding:10px;"/>
	{elseif isset($template_variables['map_used']) && !$template_variables['map_used']}
		<img src="{$baseUri}images/map-circle-inactive.png" title="{_"Searched globally because not enough was found around your location."}" style="float:right;padding:10px;"/>
	{/if}
</div>
<div class="lister-body">
   {snippet list_body}

		{ifset $template_variables['format_date_time']}
			{var $format_date_time => $template_variables['format_date_time']}
		{else}
			{var $format_date_time => "j.n.Y"}
		{/if}

    <div class="list-header-wrapper">
        <div class="list-header-name">
		{if isset($data) && isset($template_variables['show_extended_columns']) }
			{_"Name"}
		{/if}
        </div>
		{ifset $template_variables['administration']}
		<div class="list-header-role">
			{_"Role"}
		</div>
		<div class="list-header-active">
			{_"Is active"}
		</div>
		{else}
			{ifset $template_variables['show_extended_columns']}
		<div class="list-header-connections">
				{if count($lister_type) == 1}
			{_"Friends"}
				{/if}
		</div>
			{/if}
		{/if}
    </div>


{if isset($data) && count($data)>0 }

    {var $number_displayed}
	{? $number_displayed=0}
	
	{foreach $data as $row}
	{? $number_displayed++}

	{var $fullname => User::getFullName($row['id'])}	
	{var $avatar => User::getImage($row['id'], 'icon')}
	{ifset $template_variables['show_online_status']}
		{var $last_activity_a => User::getRelativeLastActivity($row['id'], $format_date_time)}
		{var $last_activity => $last_activity_a['last_seen']}
	{/if}
	
    {if $number_displayed==1 && !isset($template_variables['detail']) && !isset($template_variables["persistent_filter"]) && !isset($template_variables["recommendations"])}
    	<div class="list-body-top-wrapper">
    {/if}
        	<div class="item{ifset $template_variables['selected_row']}{if $template_variables['selected_row'] == $row['id']} selected_row{/if}{/if}"{if isset($template_variables['front_page']) || isset($template_variables['connection_columns']) || isset($template_variables['friend_lister'])}
        	{if Auth::isAuthorized(1,$row['id']) > Auth::UNAUTHORIZED}onClick="showObjectDetail(1,{$row['id']},'{!$baseUri}user/?user_id={$row['id']}')"{/if}
			{elseif isset($template_variables['user_group_resource_page'])}  onClick="showObjectDefault(1,{$row['id']})"{/if} {ifset $template_variables['show_last_activity']}onmouseover="$('#status_{$row['id']}').show();" onmouseout="$('#status_{$row['id']}').hide();"{/if}>

				<div class="icon_user online-status-title" title="<h4>{$fullname}</h4>{ifset $template_variables['show_online_status']}{$last_activity}{/if}" name="{$fullname}" object_id="{$row['id']}">
					{!$avatar}
				</div>

				<div class="list-body-name" {if isset($template_variables['group_edit_member_lister']) || isset($template_variables['resource_edit_subscriber_lister'])} onClick="showObjectDetail(1,{$row['id']},'{!$baseUri}user/?user_id={$row['id']}')"{/if}>
					{ifset $template_variables['detail']}
						{if $template_variables['detail'] == "ajax"}
            				<span class="online-status-title{if $row['status']==0} status-disabled{/if}" title="<h4>{$fullname}</h4>{ifset $template_variables['show_online_status']}{$last_activity}{/if}" name="{$fullname}" object_id="{$row['id']}">{$row['name']}</span>
						{/if}
					{else}
        		       	{if Auth::isAuthorized(1,$row['id']) > Auth::UNAUTHORIZED}
	               			<span class="online-status-title{if $row['status']==0} status-disabled{/if}" title="<h4>{$fullname}</h4>{ifset $template_variables['show_online_status']}{$last_activity}{/if}" name="{$fullname}" object_id="{$row['id']}">{$row['name']}</span>
        				{else}
        	       			<em>{_"Hidden user"}</em>
        	       		{/if}
					{/if}
					{ifset $template_variables['show_online_status']}
							<div class="online-status-small" object_id="{$row['id']}" style="display:inline;padding:3px 5px;position:absolute;bottom:0;"></div>
					{/if}
				</div>

			{ifset $template_variables['show_last_activity']}
				<div class="online-status-small" object_id="{$row['id']}" style="display:inline;padding:3px 5px;position:absolute;bottom:0;"></div>
				<div class="online-status" id="status_{$row['id']}" object_id="{$row['id']}" style="display:none;"></div>
			{/if}

		{ifset $template_variables['your_connections']} {* For home page (my connections) *}
		{? $user=User::create($row['id']); $access_level=$user->getAccessLevel()}
			{if $access_level==3}
				<div class="list-body-permissions">
					<b class="icon-administrator" title="{_"administrator"}"></b>
				</div>
			{elseif $access_level==2}
				<div class="list-body-permissions">
					<b class="icon-moderator" title="{_"moderator"}"></b>
				</div>
			{/if}
		{/if}
			
			{ifset $template_variables['administration']}
				{ifset $template_variables['persistent_filter']['group_id']}
				{if Auth::ADMINISTRATOR == Auth::isAuthorized(2,$template_variables['persistent_filter']['group_id'])}
					{var formName => $row['type_name'] . 'form' . $row['id']}
					{var $grp => Group::create($template_variables['persistent_filter']['group_id'])}
			 {if $row['type_name'] == "user" && $grp->getOwner()->getUserId() == $row['id']}
				<div class="list-body-owner">
				   {_"Owner"}
				</div>
			 {else}
					{control $formName begin}
				{ifset $control[$formName]['access_level']}
				<div class="list-body-access">
				{$control[$formName]['access_level']->control}
				</div>
				{/if}
				<div class="list-body-status">
					{$control[$formName]['status']->control}
				</div>

				<div class="list-body-send">
					{$control[$formName]['send']->control}
				</div>
					{control $formName end}
					{/if}				
			{else}
					{ifset $template_variables['show_extended_columns']}
					<div class="list-body-links">{$row['links']}</div>
					{/if}
			{/if}
			{elseifset $template_variables['persistent_filter']['resource_id']}
					{if Auth::ADMINISTRATOR == Auth::isAuthorized(3,$template_variables['persistent_filter']['resource_id'])}
			 {var formName => $row['type_name'] . 'form' . $row['id']}
					{var $res => Resource::create($template_variables['persistent_filter']['resource_id'])}
					{if $row['type_name'] == "user" && $res->getOwner()->getUserId() == $row['id']}
				<div class="list-body-owner">
					{_"Owner"}
				</div>
				{else}

				{control $formName begin}
				{ifset $control[$formName]['access_level']}
				<div class="list-body-access">
					{$control[$formName]['access_level']->control}
				</div>
				{/if}
				<div class="list-body-status">
					{$control[$formName]['status']->control}
				</div>

				<div class="list-body-send">
					{$control[$formName]['send']->control}
				</div>
				{control $formName end}
						{/if}
				{else}
					{ifset $template_variables['show_extended_columns']}
						<div class="list-body-links">{$row['links']}</div>
					{/if}
				{/if}
				
				{elseifset $template_variables['persistent_filter']['user_id']}
						{if Auth::ADMINISTRATOR == Auth::isAuthorized(1,$template_variables['persistent_filter']['user_id'])}
				 {var formName => $row['type_name'] . 'form' . $row['id']}
				 {control $formName begin}
				 {ifset $control[$formName]['access_level']}
				<div class="list-body-access">
					{$control[$formName]['access_level']->control}
				</div>
				 {/if}
				<div class="list-body-status">
					{$control[$formName]['status']->control}
				</div>

				<div class="list-body-send">
					{$control[$formName]['send']->control}
				</div>
				 {control $formName end}

				{else}
					{ifset $template_variables['show_extended_columns']}
				<div class="list-body-links">{$row['links']}</div>
					{/if}
				{/if}

					{else}
						{if Auth::ADMINISTRATOR == Auth::isAuthorized($row['type'],$row['id'])}
				 {var formName => $row['type_name'] . 'form' . $row['id']}
				 {control $formName begin}
				 {ifset $control[$formName]['access_level']}
				<div class="list-body-access">
					{$control[$formName]['access_level']->control}
				</div>
				 {/if}
				<div class="list-body-status">
					{$control[$formName]['status']->control}
				</div>

				<div class="list-body-send">
					{$control[$formName]['send']->control}
				</div>
				 {control $formName end}

				 {else}
					{ifset $template_variables['show_extended_columns']}
				<div class="list-body-links">{$row['links']}</div>
					{/if}
				 {/if}
					{/if}
			{else}
				{ifset $template_variables['show_extended_columns']}
				<div class="list-body-links">{$row['links']}</div>
				{/if}
			{/if}
			</div>
    {if $number_displayed==3 && !isset($template_variables['detail']) && !isset($template_variables["persistent_filter"]) && !isset($template_variables["recommendations"]) }
    	</div>
    {/if}
    {/foreach}
    {if $number_displayed<3 && !isset($template_variables['detail']) && !isset($template_variables["persistent_filter"])  && !isset($template_variables["recommendations"]) }
    	</div>
    {/if}
	
{else}
	<div class="not-found">
	{if $active_filter && !isset($template_variables['recommendations']) }
		{_"Nothing found."}
	{else}
		{_"Nothing to display"}
	{/if}
	</div>
{/if}

{/snippet}
</div>
<div class="lister-footer">
{snippet list_pager}
{ifset $template_variables['detail']}
	{if $currentpage == $max_page}
		{if $active_filter}
	   		<a id="filter_box_a" title="{_"Change the filter"}" href="#filter_container"><b class="filter"></b></a>
   		{/if}
	{/if}
{/if}


{if isset($template_variables['detail']) || isset($template_variables['your_connections']) || isset($template_variables['membership_detail']) || isset($template_variables['connection_columns']) || isset($template_variables['recommendations'])}
<div class="pager">
   {if $max_page > 1}
   		<a href="javascript:void(0)" {if $currentpage!=1}onclick="changePageUrl({$template_variables['name']}, 1, {link this});"{/if} class="pager-start{if $currentpage == 1} active{else}noclick{/if}">1</a>
   {/if}
   
   {if $max_page > 7}
   {if $currentpage > 5}
    	<a href="javascript:void(0)" onclick="changePageUrl({$template_variables['name']}, {$currentpage - 1}, {link this});" class="pager-minus"><</a>
   {/if}
   {/if}
   
   {if $max_page > 2}
   {if $max_page < 8}
   {for $i = 2; $i <= $max_page-1; $i++}
    	<a href="javascript:void(0)" {if $currentpage!=$i}onclick="changePageUrl({$template_variables['name']}, {$i}, {link this});"{/if}" class="pager-number{if $currentpage == $i} active{else}noclick{/if}">{$i}</a>
   {/for}   
   {else}
   {if $currentpage <= 5}
   {? if ($currentpage+4 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = 2; $i <= $end; $i++}
    	<a href="javascript:void(0)" {if $currentpage!=$i}onclick="changePageUrl({$template_variables['name']}, {$i}, {link this});"{/if}" class="pager-number{if $currentpage == $i} active{else}noclick{/if}">{$i}</a>
   {/for}
   {else}
   {? if ($currentpage+2 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = $currentpage-2; $i <= $end; $i++}
    	<a href="javascript:void(0)" {if $currentpage!=$i}onclick="changePageUrl({$template_variables['name']}, {$i}, {link this});"{/if}" class="pager-number{if $currentpage == $i} active{else}noclick{/if}">{$i}</a>
   {/for}
   {/if}
   {/if}
   {/if}

   {if $max_page > 7}
   {if ($currentpage + 4) < $max_page}
		<a href="javascript:void(0)" onclick="changePageUrl({$template_variables['name']}, {$currentpage + 1}, {link this});" class="pager-plus">></a>
   {/if}
   {/if}
   
   {if $max_page > 1}
   		<a href="javascript:void(0)" onclick="changePageUrl({$template_variables['name']}, {$max_page}, {link this});" class="pager-end{if $currentpage == $max_page} active{else}noclick{/if}">{$max_page}</a>
   {/if}
</div>

	{ifset $template_variables['detail']}
		{ifset $template_variables["persistent_filter"]}
	   	<a id="filter_box_a" title="{_"Cannot find what you are searching?"}" href="#filter_container"><b class="ajax filter"></b>{_"Try a different filter."}</a>
		{/if}
	{/if}

{else}
{if !isset($template_variables["persistent_filter"])}
		<a href="{plink User:default}" class="ajax show-more">+ {_"more users"}</a>
{/if}
{/if}
{/snippet}
</div>
