<div class="lister-header">
</div>
<div class="lister-body">
   {snippet list_body}

{ifset $template_variables['trash_enabled']}
<div id="empty-trash">
	{control emptytrashform}
</div>
{/if}

	
{if isset($data) && count($data)>0 }
	{foreach $data as $row}    
		{? $id=$row['id']}
		{var $res => Resource::Create($row['id'])}
		{var $resdata => $res->getResourceData()}
		{? $all_recipient_data = $res->getAllMembers(array('resource_id'=>$id))}
		{? $recipient_data = $all_recipient_data[0]}
		{? $recipient_id = $recipient_data['member_id']}
		{? $recipient_full_name = User::getFullName($recipient_id)}
		{if $res->getOwner()->getUserId() == $user_id}
			{? $own_message=true}
		{else}
			{? $own_message=false}
		{/if}
		{* ? $need_js_reply = true *}
		{? $user_data = $res->getOwner()->getUserData()}
		{? $sender_id = $res->getOwner()->getUserId()}
		
		{? $date=(array)$resdata['resource_creation_date']}
		{? date_default_timezone_set($date['timezone'])}
		{? $date_formatted = strftime('%e.%m.%Y %H:%I:%S',strtotime($date['date']))}

		<div class="chat-item{if $resdata['resource_type']==9} system-message{/if}" id="chat_message_{$id}"  style="{if $resdata['resource_type']==9}background-color:#F7D6A8;{/if}">
			<div class="chat-header 
				{ifset $user_id}
					{if ($resdata['resource_type'] == 1 || $resdata['resource_type'] == 8)}
						{if $own_message}
							sent-by-me
						{/if}
					{/if}
				{/if}">

				{if !isset($template_variables['logged_user_id']) || $sender_id != $template_variables['logged_user_id']}
				<div class="chat-avatar">
				{ifset $template_variables['logged_user_id']}
				<div style="width=0;height:0;border-right: 7px solid #BCB6AA;border-top: 7px solid transparent; border-bottom: 7px solid transparent;display:inline-block;float:left;margin:1px 15px;" title="{_"from %s", $user_data['user_login']}"></div>
				{/if}
					{if $res->getOwner()->isActive() || Auth::MODERATOR<=Auth::isAuthorized(1,$sender_id)}<a href="/user/?user_id={$sender_id}" title="{$user_data['user_name']} {$user_data['user_surname']}">{? echo User::getImage($sender_id, 'icon')}</a>
					{else}{? echo User::getImage($sender_id, 'icon')}{/if}
				</div>
				<div class="chat-author" id="{$id}_author" rel="{$sender_id}">
					{if $res->getOwner()->isActive() || Auth::MODERATOR<=Auth::isAuthorized(1,$sender_id)}<a href="/user/?user_id={$sender_id}" title="{$user_data['user_name']} {$user_data['user_surname']}">{$user_data['user_login']}</a>{else}{$user_data['user_login']}{/if}
				</div>

				{/if}

				{if isset($recipient_data['member_name']) && $recipient_id != $sender_id}
					{if isset($template_variables['logged_user_id']) && $recipient_id != $template_variables['logged_user_id']}
				<div style="width=0;height:0;border-left: 7px solid #BCB6AA;border-top: 7px solid transparent; border-bottom: 7px solid transparent;display:inline-block;float:left;margin:1px 15px;" title="{_"to %s", $recipient_data['member_name']}"></div>
				
				<div class="chat-avatar">
					{if $res->getOwner()->isActive() || Auth::MODERATOR<=Auth::isAuthorized(1,$recipient_id)}<a href="/user/?user_id={$recipient_id}" title="{$recipient_full_name}">{? echo User::getImage($recipient_id, 'icon')}</a>
					{else}{? echo User::getImage($sender_id, 'icon')}{/if}
				</div>
				<div class="chat-author" id="{$id}_author" rel="{$sender_id}">
					{if $res->getOwner()->isActive() || Auth::MODERATOR<=Auth::isAuthorized(1,$recipient_id)}<a href="/user/?user_id={$recipient_id}" title="{$recipient_full_name}">{$recipient_data['member_name']}</a>{else}{$recipient_data['member_name']}{/if}
				</div>
					{/if}
				{/if}
								
				<div id="{$id}_date" class="chat-time">{$date_formatted}</div>

					{ifset $template_variables['moderation_enabled']}
					{if Auth::MODERATOR<=Auth::isAuthorized(3,$template_variables['resource_id'])}
						<div class="move-to-trash">
							<a id="totrash-{$id}" href="javascript:void(0);" onClick="removeMessage({$id});" title="{_"Remove this message."}"><b class="icon-message-to-trash"></b></a>	
						</div>
					{/if}
					{/if}
					
					{ifset $template_variables['trash_enabled']}
						<div class="move-to-trash">
							<a id="totrash-{$row['id']}" href="javascript:void(0);" onClick="moveToTrash({$row['id']});$('#totrash-{$row['id']}').hide();$('#fromtrash-{$row['id']}').show();$('#chat_message_{$row['id']}').hide('normal');"><b class="icon-message-to-trash" title="{_"move to trash"}"></b></a>	
						</div>

						<div class="restore-from-trash">
							<a id="fromtrash-{$row['id']}" href="javascript:void(0);" onClick="moveFromTrash({$row['id']});$('#fromtrash-{$row['id']}').hide();$('#totrash-{$row['id']}').show();$('#chat_message_{$row['id']}').hide('normal');"><b class="icon-message-from-trash" title="{_"restore from trash"}"></b></a>
						</div>

						<script>
							$(document).ready(function(){
							{if $res->inTrash()}
								$("#totrash-{$row['id']}").hide();
							{else}
								$("#fromtrash-{$row['id']}").hide();
							{/if}
							});
						</script>
					{/if}

					{ifset $template_variables['mark_read_enabled']}
						<div class="read-status">
							<a id="markread-{$row['id']}" href="javascript:void(0);" onClick="markRead({$row['id']});$('#markread-{$row['id']}').hide();$('#markunread-{$row['id']}').show(); if ($('#frmfilter-trash-0').is(':checked')){ $('#chat_message_{$row['id']}').hide('normal');}"><b class="icon-message-unread" title="{_"mark as read"}"></b></a>							
							<a id="markunread-{$row['id']}" href="javascript:void(0);" onClick="markUnread({$row['id']});$('#markunread-{$row['id']}').hide();$('#markread-{$row['id']}').show();"><b class="icon-message-read" title="{_"mark as unread"}"></b></a>
						</div>
			
						<script>
							$(document).ready(function(){
							{if $res->isOpened()}
								$("#markread-{$row['id']}").hide();
							{else}
								$("#markunread-{$row['id']}").hide();
							{/if}
							{if $own_message}
								$("#markunread-{$row['id']}").hide();
							{/if}
							});
						</script>
					{/if}

				{if isset($own_message) && !$own_message && isset($template_variables['reply_enabled']) && $res->getOwner()->isActive()}
				<div class="chat-reply">
					<a href="javascript:void(0);" id="reply_0000{$id}" class="button">{_"reply"}</a>
				</div>
				{/if}
			</div> <!-- .chat-header -->

				<div id="{$id}_text" class="chat-text" style="{if $own_message}background-color:#F7F7F7;{/if}padding:0.7em 0.3em;">
				{if $res->getOwner()->isActive() || Auth::MODERATOR<=Auth::isAuthorized(1,$sender_id)}
					{if !$res->getOwner()->isActive()}
					<p class="chat-inactive" style="color:#C00;">{_"User has been deactivated"}</p>
					{/if}
					{!$resdata['message_text']|htmlpurify}
				{else}
					<span class="chat-inactive" style="color:#CCC;">{_"Message not displayed because the user has been deactivated."}</span>
				{/if}
				</div>

		</div>
    {/foreach}
{else}
<h4>{_"No messages"}</h4>
{/if}

{/snippet}
</div>

{ifset $template_variables['reply_enabled']}
<script>
	$(document).ready(function(){
		$('blockquote').css({ "cursor":"pointer"});
			
		$('[id^=reply_]').click(function(){
			var id = parseInt($(this).attr('id').substr(-5,5));
			var editor = tinymce.editors[0];
			var content = editor.getContent();
			var quote = $('[id$='+id+'_text]').html();
			quote = quote.replace(/(<([^>]+[^(blockquote)])>)/ig,"");
			var author_name = $('[id$='+id+'_author]').html();
			var author_id = $('[id$='+id+'_author]').attr('rel');
			var date = $('[id$='+id+'_date]').html();
			var quote_shortened = quote.substr(0,300);
			if (quote_shortened != quote ) { quote_shortened += '...'; }
			$('#frmmessageform-friend_id').val(author_id);
			var reply = '<br/><blockquote id="quoting_0000'+id+'"><span style="color:#333;">{!_"On"} <b>'+date+'</b></span> <b><span style="color:#999;">'+author_name+'</span></b> <span style="color:#333;">{!_"wrote"}:</span><br />'+quote_shortened+'</blockquote><br/>';
			content = reply;
			editor.setContent(content);
			$('html, body').animate({
				scrollTop: $("#message_top_anchor").offset().top
			}, 2000);
			editor.focus();
			markRead(id);
			$('#markread-'+id).hide();
			$('#markunread-'+id).show();
		});
	
		$('blockquote').click(function(){
			var id = parseInt($(this).attr('id').substr(-5,5));
			$('html, body').animate({
				scrollTop: $("#chat_message_"+id).offset().top
			}, 'normal');
		});
	
		$('blockquote').mouseover(function(){
			var id = parseInt($(this).attr('id').substr(-5,5));
			$("#chat_message_"+id).css({ "border-left":"solid 4px #E08E1B", "padding-left":"20px"});
			if ($("#chat_message_"+id).css("border-left")) {
				$(this).css('cursor','pointer');
			};
		});

		$('blockquote').mouseout(function(){
			var id = parseInt($(this).attr('id').substr(-5,5));
			$("#chat_message_"+id).css({ "border-left":"inherit", "padding-left":"0"});
		});
	
	});
</script>
{/if}

{ifset $template_variables['moderation_enabled']}
<script>
		function removeMessage(id) {
			$('#chat_message_'+id).css({'background-color':'#E30'});
			var resource_id={$template_variables['resource_id']};
			setTimeout( function(){
				reply=confirm({_"Do you really want to delete this message?"});
				if (reply==true) {
					$.post("?message_id="+id+"&resource_id="+resource_id+"&do=removeMessage");
						$('#totrash-'+id).hide();
						$('#chat_message_'+id).hide('normal');
				} else {
					$('#chat_message_'+id).css({'background-color':'transparent'});
				}	
			}, 500 );	
		}	
</script>
{/if}


<div class="lister-footer">
{snippet list_pager}

<div class="pager">
   {if $max_page > 1}
   		<a href="{link changePage, page => 1}" class="pager-start{if $currentpage == 1} active{/if}">1</a>
   {/if}
   
   {if $max_page > 5}
   {if $currentpage > 4}
    	<a href="{link changePage, page => $currentpage - 1}" class="pager-minus"><</a>
   {/if}
   {/if}
   
   {if $max_page > 2}
   {if $max_page < 6}
   {for $i = 2; $i <= $max_page-1; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}   
   {else}
   {if $currentpage <= 4}
   {? if ($currentpage+2 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = 2; $i <= $end; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}
   {else}
   {? if ($currentpage+3 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = $currentpage-2; $i <= $end; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}
   {/if}
   {/if}
   {/if}

   {if $max_page > 5}
   {if ($currentpage + 3) < $max_page}
		<a href="{link changePage, page => $currentpage + 1}" class="pager-plus">></a>
   {/if}
   {/if}
   
   {if $max_page > 1}
   		<a href="{link changePage, page => $max_page}" class="pager-end{if $currentpage == $max_page} active{/if}">{$max_page}</a>
   {/if}
</div>

{/snippet}
</div>
