<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<div class="lister-header">
</div>
<div class="lister-body">
   {snippet list_body}

    <div class="list-header-wrapper">
        <div class="list-header-name">
		{if isset($data) && isset($template_variables['show_extended_columns']) }
			{_"Name"}
		{/if}
        </div>
			{ifset $template_variables['administration']}
					<div class="list-header-role">
						{_"Role"}
					</div>
					<div class="list-header-active">
						{_"Is active"}
					</div>
			{else}
				{ifset $template_variables['show_extended_columns']}
				<div class="list-header-connections">
					{if count($lister_type) == 1}
							{_"Friends"}
					{/if}
				</div>
				{/if}
			{/if}

    </div>


{if isset($data) && count($data)>0 }

    {var $number_displayed}
	{? $number_displayed=0}
	
	{foreach $data as $row}
	{? $number_displayed++}

    {if $number_displayed==1 && !isset($template_variables['detail']) && !isset($template_variables["persistent_filter"]) }
    	<div class="list-body-top-wrapper">
    {/if}
			{? $id=$row['id']}
        	{? $color='transparent'}    
        	<div class="item{ifset $template_variables['selected_row']}{if $template_variables['selected_row'] == $row['id']} selected_row{/if}{/if}"{if isset($template_variables['front_page']) || isset($template_variables['connection_columns']) || isset($template_variables['friend_lister'])}
        	{if Auth::isAuthorized(1,$row['id'])>0}onClick="window.location = '/user/?user_id={$row['id']}'{/if}"
			{elseif isset($template_variables['user_group_resource_page'])}{* user, group, resource lists *}  onClick="showObjectDetail({$row['type']},{$row['id']})"{/if}>
						{var $fullname => User::getFullName($row['id'])}
						<div class="icon_user" title="{$fullname}">
							{? echo User::getImage($row['id'], 'icon')}
						</div>

				<div class="list-body-name" {if isset($template_variables['group_edit_member_lister']) || isset($template_variables['resource_edit_subscriber_lister'])}onClick="window.location = '/user/?user_id={$row['id']}'"{/if}>
					{ifset $template_variables['detail']}
						{if $template_variables['detail'] == "ajax"}
            				<span title="{$fullname}">{$row['name']}</span>
						{/if}
					{else}
						{var $fullname => User::getFullName($row['id'])}
        		       	{if Auth::isAuthorized(1,$row['id'])>0}
	               			<span title="{$fullname}">{$row['name']}</span>               	
        				{else}
        	       			<em>{_"Hidden user"}</em>
        	       		{/if}
					{/if}
				</div>

		{ifset $template_variables['your_connections']} {* For home page (my connections) *}
		{? $user=User::create($row['id']); $access_level=$user->getAccessLevel()}
			{if $access_level==3}
				<div class="list-body-permissions">
					<b class="icon-administrator" title="{_"administrator"}"></b>
				</div>
			{elseif $access_level==2}
				<div class="list-body-permissions">
					<b class="icon-moderator" title="{_"moderator"}"></b>
				</div>
			{/if}
		{/if}
				


				 	{ifset $template_variables['administration']}
						{ifset $template_variables['persistent_filter']['group_id']}
				 		{if Auth::ADMINISTRATOR == Auth::isAuthorized(2,$template_variables['persistent_filter']['group_id'])}
        					{var formName => $row['type_name'] . 'form' . $row['id']}
							{var $grp => Group::create($template_variables['persistent_filter']['group_id'])}
                     {if $row['type_name'] == "user" && $grp->getOwner()->getUserId() == $row['id']}
                        <div class="list-body-owner">
                           {_"Owner"}
                        </div>
                     {else}
        					{control $formName begin}
            			{ifset $control[$formName]['access_level']}
            			<div class="list-body-access">
               			{$control[$formName]['access_level']->control}
            			</div>
            			{/if}
            			<div class="list-body-status">
                			{$control[$formName]['status']->control}
            			</div>

            			<div class="list-body-send">
                			{$control[$formName]['send']->control}
            			</div>
        					{control $formName end}
							{/if}				
            		{else}
							{ifset $template_variables['show_extended_columns']}
								<div class="list-body-links">{$row['links']}</div>
							{/if}
            		{/if}
					{elseifset $template_variables['persistent_filter']['resource_id']}
							{if Auth::ADMINISTRATOR == Auth::isAuthorized(3,$template_variables['persistent_filter']['resource_id'])}
                     {var formName => $row['type_name'] . 'form' . $row['id']}
							{var $res => Resource::create($template_variables['persistent_filter']['resource_id'])}
							{if $row['type_name'] == "user" && $res->getOwner()->getUserId() == $row['id']}
               			<div class="list-body-owner">
                  			{_"Owner"}
               			</div>
            			{else}

                    {control $formName begin}
                    {ifset $control[$formName]['access_level']}
                     <div class="list-body-access">
                        {$control[$formName]['access_level']->control}
                     </div>
                    {/if}
                     <div class="list-body-status">
                        {$control[$formName]['status']->control}
                     </div>

                     <div class="list-body-send">
                        {$control[$formName]['send']->control}
                     </div>
                     {control $formName end}
							{/if}
                  	{else}
						{ifset $template_variables['show_extended_columns']}
							<div class="list-body-links">{$row['links']}</div>
						{/if}
                  	{/if}
					
					{elseifset $template_variables['persistent_filter']['user_id']}
							{if Auth::ADMINISTRATOR == Auth::isAuthorized(1,$template_variables['persistent_filter']['user_id'])}
                     {var formName => $row['type_name'] . 'form' . $row['id']}
                     {control $formName begin}
                     {ifset $control[$formName]['access_level']}
                     <div class="list-body-access">
                        {$control[$formName]['access_level']->control}
                     </div>
                     {/if}
                    <div class="list-body-status">
                    	{$control[$formName]['status']->control}
                    </div>

                     <div class="list-body-send">
                        {$control[$formName]['send']->control}
                     </div>
                     {control $formName end}

                    {else}
						{ifset $template_variables['show_extended_columns']}
							<div class="list-body-links">{$row['links']}</div>
						{/if}
                    {/if}

						{else}
							{if Auth::ADMINISTRATOR == Auth::isAuthorized($row['type'],$row['id'])}
                     {var formName => $row['type_name'] . 'form' . $row['id']}
                     {control $formName begin}
                     {ifset $control[$formName]['access_level']}
                     <div class="list-body-access">
                        {$control[$formName]['access_level']->control}
                     </div>
                     {/if}
                     <div class="list-body-status">
                        {$control[$formName]['status']->control}
                     </div>

                     <div class="list-body-send">
                        {$control[$formName]['send']->control}
                     </div>
                     {control $formName end}

                     {else}
						{ifset $template_variables['show_extended_columns']}
                        	<div class="list-body-links">{$row['links']}</div>
						{/if}
                     {/if}
						{/if}
				{else}
					{ifset $template_variables['show_extended_columns']}
                     	<div class="list-body-links">{$row['links']}</div>
					{/if}
				{/if}
			</div>	
    {if $number_displayed==3 && !isset($template_variables['detail']) && !isset($template_variables["persistent_filter"]) }
    	</div>
    {/if}
    {/foreach}
    {if $number_displayed<3 && !isset($template_variables['detail']) && !isset($template_variables["persistent_filter"]) }
    	</div>
    {/if}
	
{else}
	<div class="not-found">
	{if $active_filter}
		{_"Nothing found."} <a id="filter_box_a" title="{_"Change the filter"}" href="#filter_container"><b class="icon-filter"></b></a></div>
	{else}
		{_"Nothing to display"}
	{/if}
	</div>
{/if}

{/snippet}
</div>
<div class="lister-footer">
{snippet list_pager}
{ifset $template_variables['detail']}
	{if $currentpage == $max_page}
		{if $active_filter}
	   		<a id="filter_box_a" title="{_"Change the filter"}" href="#filter_container"><b class="filter"></b></a>
   		{/if}
	{/if}
{/if}


{if isset($template_variables['detail']) || isset($template_variables['your_connections']) || isset($template_variables['membership_detail']) || isset($template_variables['connection_columns'])}
<div class="pager">
   {if $max_page > 1}
   		<a href="{link changePage, page => 1}" class="pager-start{if $currentpage == 1} active{/if}">1</a>
   {/if}
   
   {if $max_page > 5}
   {if $currentpage > 4}
    	<a href="{link changePage, page => $currentpage - 1}" class="pager-minus"><</a>
   {/if}
   {/if}
   
   {if $max_page > 2}
   {if $max_page < 6}
   {for $i = 2; $i <= $max_page-1; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}   
   {else}
   {if $currentpage <= 4}
   {? if ($currentpage+2 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = 2; $i <= $end; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}
   {else}
   {? if ($currentpage+3 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = $currentpage-2; $i <= $end; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}
   {/if}
   {/if}
   {/if}

   {if $max_page > 5}
   {if ($currentpage + 3) < $max_page}
		<a href="{link changePage, page => $currentpage + 1}" class="pager-plus">></a>
   {/if}
   {/if}
   
   {if $max_page > 1}
   		<a href="{link changePage, page => $max_page}" class="pager-end{if $currentpage == $max_page} active{/if}">{$max_page}</a>
   {/if}
</div>

	{ifset $template_variables['detail']}
		{ifset $template_variables["persistent_filter"]}
	   		<a id="filter_box_a" title="{_"Cannot find what you are searching?"}" href="#filter_container"><b class="filter"></b>{_"Try a different filter."}</a>
		{/if}
	{/if}

{else}
{if !isset($template_variables["persistent_filter"])}
		<a href="{plink User:default}" class="show-more">+ {_"more users"}</a>
{/if}
{/if}
{/snippet}
</div>
