<div class="menu-table {$name}">
<table>
{var $i => 0,$j => 0}
<tr>
{foreach $data as $key=>$menuitem}
	{if $j >= $columns}
		{var $j => 0}
		{var $i => $i+1}
		</tr>
		</tr>
	{/if}
	<td>
		<a href="{$menuitem['url']}" title="{$menuitem['title']}" style="display:block;">
		<div class="column-item">
			<div class="column-content">
				{!$menuitem['content']}
			</div>
		</div>
		</a>
	</td>
	{var $j => $j+1}
{/foreach}
</tr>
</table>
</div>
