<div class="menu-tree {$name}">
<ul id="menu" class="menu">	
{foreach $data as $key=>$menuitem}
	<li>
	<a href="{$menuitem['url']}" onClick='$("#li-content-{$menuitem['key']}").toggle();$("#ul-content-{$menuitem['key']}").toggle();'>{$menuitem['title']}</a>
	{ifset $menuitem['content']}	
	<div class="li-content" id="li-content-{$menuitem['key']}">
		{!$menuitem['content']}
	</div>
	{/if}
	{ifset $data[$key+1]}
		{if $data[$key+1]['parent'] == $menuitem['key']}
			<ul id="ul-content-{$menuitem['key']}" class="ul-content">
		{elseif $data[$key+1]['parent'] != $menuitem['parent']}
			</li>
			</ul>
			</li>
		{/if}
	{/if}
{/foreach}
</ul>
</div>
