<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<div class="menu-table {$name}">
<table>
{var $i => 0,$j => 0}
<tr>
{foreach $data as $key=>$menuitem}
	{if $j >= $columns}
		{var $j => 0}
		{var $i => $i+1}
		</tr>
		</tr>
	{/if}
	<td>
		<a href="{$menuitem['url']}" title="{$menuitem['title']}" style="display:block;">
		<div class="column-item">
			<div class="column-content">
				{!$menuitem['content']}
			</div>
		</div>
		</a>
	</td>
	{var $j => $j+1}
{/foreach}
</tr>
</table>
</div>
