<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<div class="menu-tree {$name}">
<ul id="menu" class="menu">	
{foreach $data as $key=>$menuitem}
	<li>
	<a href="{$menuitem['url']}" onClick='$("#li-content-{$menuitem['key']}").toggle();$("#ul-content-{$menuitem['key']}").toggle();'>{$menuitem['title']}</a>
	{ifset $menuitem['content']}	
	<div class="li-content" id="li-content-{$menuitem['key']}">
		{!$menuitem['content']}
	</div>
	{/if}
	{ifset $data[$key+1]}
		{if $data[$key+1]['parent'] == $menuitem['key']}
			<ul id="ul-content-{$menuitem['key']}" class="ul-content">
		{elseif $data[$key+1]['parent'] != $menuitem['parent']}
			</li>
			</ul>
			</li>
		{/if}
	{/if}
{/foreach}
</ul>
</div>
