<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.2.2 beta
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
@{extends ListerControl.phtml}
@{block #listerhead}

{/block}
@{block #listcontent}
<table>
    <tr>
        <th>
           	{_"Name"} 
        </th>
        <th>
            {_"Enabled"}
        </th>
    </tr>
	{foreach $data as $resource}
		{if (Auth::ADMINISTRATOR == Auth::isAuthorized(Auth::TYPE_RESOURCE,$resource['resource_id'])) || (Auth::isAuthorized(Auth::TYPE_RESOURCE,$resource['resource_id']) != Auth::UNAUTHORIZED && $resource['resource_status'] == 1)}
        <tr>
				<td>
					{$resource['resource_name']}
				</td>
					{if Auth::ADMINISTRATOR == Auth::isAuthorized(Auth::TYPE_RESOURCE,$resource['resource_id'])}

        {var formName => 'resourceform' . $resource['resource_id']}
        {control $formName begin}
            <td>
                {$control[$formName]['resource_status']->control}
            </td>
	

            <td>
                {$control[$formName]['send']->control}
            </td>
        {control $formName end}
				<td>
					{$resource['resource_type']}
				</td>
				<td>
               <a href="{plink Resource:edit, $resource['resource_id']}">{_"edit"}</a>
            </td>
				{else}
					<td>{$resource['resource_status']}</td>
					<td>{$resource['resource_type']}</td>
					<td></td>
				{/if}
				<td>
					<a href="{plink Resource:default, $resource['resource_id']}">{_"detail"}</a>
				</td>
        </tr>
		{/if}
    {/foreach}
</table> 
{/block}
@{block #listertail}

{/block}
