<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{extends ListerControl.phtml}
{block #listerhead}

{/block}
{block #listcontent}
<table>
    <tr>
        <th>
            Member
        </th>
		  <th>
				Member type
		  </th>		
        <th>
            Access Level
        </th>
        <th>
            Enabled
        </th>
    </tr>
	{if !empty($data)}
	{foreach $data as $member}
        <tr>
            <td>
                [{$member['member_name']}]
            </td>
				<td>
					{if $member['member_type'] == 1}
						User
					{else}
						Group
					{/if}
				</td>

        {var formName => 'userform' .$member['member_type'] .'x'. $member['member_id']}
        {control $formName begin}
            <td>
                {$control[$formName]['resource_user_group_access_level']->control}
            </td>

            <td>
                {$control[$formName]['resource_user_group_status']->control}
            </td>

            <td>
                {$control[$formName]['update']->control}
            </td>
        {control $formName end}
				{if $member['member_type'] == 1}
				<td>
					<a href="{plink User:default, $member['member_id']}">View details</a>
				</td>
				{else}
				<td>
               <a href="{plink Group:default, $member['member_id']}">View details</a>
            </td>
				{/if}
        </tr>
    {/foreach}
	 {/if}
</table> 
{/block}
{block #listertail}

{/block}
