<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
<div class="lister-header">

</div>
<div class="lister-body">
	<table class="admin-table" cellspacing="0" cellpadding="5" style="width:700px;">
    <tr>
        <th>
        	<h3>Name</h3>
        </th>
        <th>
        	<h3>Parent</h3>
        </th>
        <th>
        	<h3>Actions</h3>
        </th>
        <th>
        	<h3>Position</h3>
        </th>
        <th>
        	<h3>Usage</h3>
        </th>
    </tr>
   {foreach $data as $tag}
        <tr>
        {var formName => 'tagform' . $tag['tag_id']}
        {control $formName begin}
            <td>
                {$control[$formName]['tag_name']->control}
            </td>
            <td>
               {!$control[$formName]['tag_parent_id']->control}
            </td>
            <td>
                {$control[$formName]['send']->control}
				{$control[$formName]['remove']->control}
			</td>
            <td>
            {if $tag['tag_parent_id']==0}
            	<p><a class="button" href="?do=move&tag_id={$tag['tag_id']}&direction=up">{_"move up"}</a></p>
            	<p><a class="button" href="?do=move&tag_id={$tag['tag_id']}&direction=down">{_"move down"}</a></p>
            {/if}
			</td>
			<td>
				<table cellspacing="0" style="background-color:white; font-size:10px; margin:5px 10px;">
				<tr><td>Users:</td><td>{$tag['tag_number']['user']}</td></tr>
				<tr><td>Groups:</td><td>{$tag['tag_number']['group']}</td></tr>
				<tr><td>Resources:</td><td>{$tag['tag_number']['resource']}</td></tr>
				<tr><td><b>Total:</b></td><td><b>{$tag['tag_number']['total']}</b></td></tr>
				</table>
			</td>
        {control $formName end}
        </tr>
    {/foreach}
   </table>
</div>

<div class="pager">
   {if $max_page > 1}
   		<a href="{link changePage, page => 1}" class="pager-start{if $currentpage == 1} active{/if}">1</a>
   {/if}
   
   {if $max_page > 5}
   {if $currentpage > 4}
    	<a href="{link changePage, page => $currentpage - 1}" class="pager-minus"><</a>
   {/if}
   {/if}
   
   {if $max_page > 2}
   {if $max_page < 6}
   {for $i = 2; $i <= $max_page-1; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}   
   {else}
   {if $currentpage <= 4}
   {? if ($currentpage+2 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = 2; $i <= $end; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}
   {else}
   {? if ($currentpage+3 < $max_page) $end=$currentpage+2; else $end=$max_page-1}
   {for $i = $currentpage-2; $i <= $end; $i++}
    	<a href="{link changePage, page => $i}" class="pager-number{if $currentpage == $i} active{/if}">{$i}</a>
   {/for}
   {/if}
   {/if}
   {/if}

   {if $max_page > 5}
   {if ($currentpage + 3) < $max_page}
		<a href="{link changePage, page => $currentpage + 1}" class="pager-plus">></a>
   {/if}
   {/if}
   
   {if $max_page > 1}
   		<a href="{link changePage, page => $max_page}" class="pager-end{if $currentpage == $max_page} active{/if}">{$max_page}</a>
   {/if}
</div>

