<div class="intro">
<table>
<tbody><tr style="text-align:top;">
<td><h2>Social Networking for Civil Society</h2>
<h3>Mycitizen.net is a free platform for people in and from Myanmar to support citizen engagement.</h3>

<ul class="intro_list">
<li>Find people with similar interests and problems</li>
<li>Be stronger in a group</li>
<li>Plan activities together</li>
<li>Make your voice heard</li>
<li>Share important information</li>
<li>Exercise your rights safely</li>
<li>Get connected where the Internet is slow</li>
</ul>
<p><a href="/signup" target="_top" class="button">Sign up</a> or <a href="http://mycitizen.net/" target="_blank">learn more</a>.</p>
<p class="intro_community">Need this for your own community? <a href="http://mycitizen.net/web:start" target="_blank">Get involved</a>.
</p>
</td>
<td>
<div class="intro-video">
<h2>Watch our video:</h2>
    <iframe width="350" height="200" src="//www.youtube.com/embed/lvKy_og2QhI?rel=0&showinfo=0" frameborder="0" allowfullscreen=""></iframe>
</div>
</td>
</tr>
</tbody></table>
</div>