<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Administration - Reports"}{/block}
{block content}
	<div class="menu_admin">
	{control adminmenu}
	</div>
<div class="wrapper-text">
	<h1>{_"Reports"}</h1>
	{control reportlister}
</div>
{/block}
