<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Administration - Setup and Maintenance"}{/block}
{block content}
<div class="menu_admin">
	{control adminmenu}
</div>
<div class="wrapper-text">
	<h1>{_"Setup and Maintenance"}</h1>
	<table class="admin-table" style="min-width:700px;" cellspacing="0">

	<tr class="tr-header">
		<td colspan="2">
			<h3>System Information</h3>
		</td>
	</tr>
	<tr>
		<td><b>{_"PHP Version"}</b></td><td>{? echo PHP_VERSION}</td>
	</tr>
	<tr>
		<td><b>{_"MySQL Version"}</b></td><td>{$MySQL_version}</td>
	</tr>
	<tr>
		<td><b>{_"Database size"}</b></td><td>{$database_size} MB</td>
	</tr>
	<tr>
		<td><b>{_"PHP max execution time"}</b></td><td>{? echo ini_get('max_execution_time'); } sec</td>
	</tr>
	<tr>
		<td><b>{_"PHP memory limit"}</b></td><td>{? echo ini_get('memory_limit'); }</td>
	</tr>
	<tr>
	{? $base = log(memory_get_usage()) / log(1024)}
	{? $suffix = array("", "k", "M", "G", "T");}
		<td><b>{_"PHP memory usage"}</b></td><td>{? echo round(pow(1024, $base - floor($base)),1) . $suffix[floor($base)] }</td>
	</tr>
	<tr>
		<td><b>{_"GD (images) supported"}</b></td><td>{if function_exists("ImageCreateTrueColor")}yes{else}<span style="color:#f00;">no</span>{/if}</td>
	</tr>
	<tr>
		<td><b>{_"Software version:"}</b></td><td> {$PROJECT_VERSION}</td>
	</tr>
{ifset $new_version}
	<tr>
		<td><b style="color:#f00;">{_"New version:"}</b></td><td> <span style="color:#f00;">{$new_version}</span></td>
	</tr>
	<tr>
		<td><b>{_"Release information:"}</b></td><td> {$new_version_info}</td>
	</tr>
	<tr>
		<td></td><td><a href="https://mycitizen.net/download:web" target="_blank" class="button">{_"More information and download"}</a></td>
	</tr>
{else}
	<tr>
		<td></td><td>{_"Your software is up to date."}</a></td>
	</tr>

{/if}
	<tr class="tr-header">
		<td colspan="2">	
			<h3>Setup</h3>
		</td>
	</tr>
	<tr>
		<td><a href="?do=import" class="button">{_"Import resources from a file"}</a></td><td><img src="{$baseUri}/images/help.png" class="help-icon" title="
	Imports resources from a file that is named <b>resources.csv</b> and located in the web/files folder.
	<br/>The data must be provided in tab-separated values, text in enclosing quotes. Lines that start with # will be skipped (use it for column lables and comments).
	<br/><br/><b>Columns</b> (in this order)
	<br/>Name, Description, Type [organization, document, youtube, vimeo, soundcloud, bambuser, other], Location (recommended: 'country' or 'town, country' or 'street, town, country'; must be understood by Google Maps), URL, Media Code (for multimedia), Long Info (for documents), Language (id; default is 1), visibility (1: world, 2: registerd, 3: subscribers), Tags (comma separated names)
	<br/>Name, Description and Type are mandatory.
	<br/><b>Notes:</b> Events not yet fully supported. Processing the same file repeatedly will result in duplicates. Don't delete a language that anyone is using.
	<br/>
	<br/>After processing, you will find an error log with the name 'resources.csv.log'.
	<br/>Consult the manual for more options.
	"/></td>
	</tr>
	<tr>
		<td><a href="?do=import&test_run=1" class="button">{_"Test the import in a dry run"}</a></td><td><img src="{$baseUri}/images/help.png" class="help-icon" title="
	This will create a log file without effecting any changes."/></td>
	</tr>
	<tr>
		<td><a href="?do=locales" class="button">{_"Update languages"}</a></td><td><img src="{$baseUri}/images/help.png" class="help-icon" title="Compares the <b>locale</b> folder with languages in the database and updates the database.
		<br /><br /><b>Requirements:</b>
		<ul>
		<li>a messages.mo file in the LC_MESSAGES subfolder under the folder with the language code</li>
		<li>a language.txt file in the same subfolder, which contains the name of the language</li>
		<li>intro.phtml and footer.phtml in a subfolder with the language code, placed under files</li>
		</ul>
		"/></td>
	</tr>
	<tr>
		<td><b>{_"Cron URL:"}</b></td><td><a href="https://4development.mycitizen.net//?do=cron&token=a163ac5b0a4b8cea4da4747a823c05d9&verbose=1" target="_blank">{$baseUri}/?do=cron&token={!$token}</a><p>(Click to test in verbose mode.)</p></td>
	</tr>
	<tr>
		<td><b>{_"Set up a cron on an external service:"}</b></td><td>
		<p><img src="{$baseUri}/images/help.png" class="help-icon" title="These are some suggestions of providers. If you know of any other, please let us know!"/></p>
		<a href="https://www.easycron.com/clickschedule?url={$cron_url}&testFirst=0&specifiedBy=1&specifiedValue=10" target="_blank" class="button">Easy Cron</a></td>
	</tr>
	<tr class="tr-header">
		<td colspan="2">
			<h3>Maintenance</h3>
		</td>
	</tr>
	<tr>
		<td><a href="?do=systemcheck"  class="button">{_"System check"}</a></td>
		
		<td><img src="{$baseUri}/images/help.png" class="help-icon" title="Finds:<ul><li>groups and resources without owners.</li></ul>"/>
		</td>
	</tr>
{ifset $problem}
{if $problem}
{ifset $groups_wo_owner}
	<tr>
		<td><b>{_"Problem found"}</b></td><td>{_"Found %i groups without owner.", $groups_wo_owner}</td>
	</tr>
{/if}
{ifset $resources_wo_owner}
	<tr>
		<td><b>{_"Problem found"}</b></td><td>{_"Found %i resources without owner.", $resources_wo_owner}</td>
	</tr>
{/if}
{else}
	<tr>
		<td><b>{_"Result"}</b></td><td>{_"No problem found."}</td>
	</tr>
{/if}
{/if}
	<tr>
		<td>
			<h4>{_"Purge unconfirmed users"}</h4>
			<p><a href="?do=purgeusers&months=1"  class="button">{_"Over one month old"}</a></p>
			<p><a href="?do=purgeusers&months=2"  class="button">{_"Over two months old"}</a></p>
			<p><a href="?do=purgeusers&months=6"  class="button">{_"Over six months old"}</a></p>
		</td>
		
		<td><img src="{$baseUri}/images/help.png" class="help-icon" title="Removes users<ul><li>with unfinished registration, signed up over x months ago</li></ul>"/>
		</td>
	</tr>

	<tr class="tr-header">
		<td colspan="2">
			<h3>Support</h3>
		</td>
	</tr>
	<tr>
		<td><b>{_"Documentation:"}</b></td><td><a href="http://mycitizen.net/manual:start#mycitizennetweb" target="_blank" class="button">go to website</a></td>
	</tr>
	<tr>
		<td><b>{_"User Forum:"}</b></td><td><a href="http://forum.mycitizen.org/mycitizen-net-web" target="_blank" class="button">go to forum</a></td>
	</tr>
	</table>	


</div>
{/block}
