<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.2.1 beta
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{var load_js_css_tree => true}
{block title}{_"Administration - Create new tag"}{/block}
{block content}
	<div class="menu_admin">
	{control adminmenu}
	</div>
<div class="wrapper-text">
	<h1>{_"Add a Tag"}</h1>
	{control registertag}	
</div>
{/block}
