<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
 
$homepage = true;
?>
{block title}Homepage{/block}
{block content}

<div class="homepage_default_A">

<div class="wrapper-intro">
{ifset $logged}
<div class="wrapper-intro-left" style="display: inline-block;">
	<h2>{_"Welcome"} {$username}!</h2>
	{ifset $access_level_welcome}
	<h4>{$access_level_welcome}<h4>
	{/if}
	{ifset $reports_pending}
	<h4>{_"There are unread reports:"} <a href="{!$reports_url}" class="button ajax">{$reports_pending}</a><h4>
	{/if}
	{ifset $incomplete_profile}
	<h4>{_"Now is the best time to complete your profile. You can enter your name, your location and tags for your interests."}</h4><p><a href="{link User:edit, $my_id}" class="button">{_"Click here to continue"}</a></p>
	{/if}
</div>
{else}
	<div class="intro">
	{include $intro}
	</div>
{/if}
</div>

{ifset $logged}{* Users who are logged in see "own" items. *}
<div class="cleaner"></div>


<div id="tabs" style="display:none;">
	<ul id="tab_headers" style="display:none;">
		<li><a href="#connections">{_"My Connections"}</a></li>
		<li><a href="#recommendations">{_"My Recommendations"}</a></li>
		<li id="tab_activity"><a href="#activity">{_"My Activity"}</a></li>
		<li id="tab_events"><a href="#events">{_"My Events"}</a></li>
{ifset $home_tabs}{foreach $home_tabs as $home_tab}{? $home_tab_data = explode(",", $home_tab)}
		<li id="tab_{$home_tab_data[0]}"><a href="#slide_{$home_tab_data[0]}">{$home_tab_data[1]}</a></li>
{/foreach}{/if}
	</ul>
<div class="wrapper-home">
	<div id="connections">

		<div class="homepage_default_filter">
			<div class="filter-body filter-body-{control homepageresourcelister:filterstatus}">
				<a href="#filter_container" id="filter_box_a" class="filter-button-{control homepageresourcelister:filterstatus}" title="{control homepageresourcelister:filtertitle}">{control homepageresourcelister:filtercheck}</a>

			</div>
		</div>
		<div class="top-users">
			<h2>{_"My Friends"}</h2>
				{control homepagefriendlister:body}
			<div class="discover_new_users">
				<a href="{link User:default}" class="ajax">{_"Discover new users"}</a>
			</div>
		</div>
		<div class="top-groups">
			<h2>{_"My Groups"}</h2>
				{control homepagegrouplister:body}
			<div class="discover_new_groups">
				<a href="{link Group:default}" class="ajax">{_"Discover new groups"}</a>
			</div>
		</div>
		<div class="top-resources">
			<h2>{_"My Resources"}</h2>
				{control homepageresourcelister:body}
			<div class="discover_new_resources">
				<a href="{link Resource:default}" class="ajax">{_"Discover new resources"}</a>
			</div>
		</div>
	</div>

	<div id="recommendations">
		<img src="{$baseUri}/images/help.png" class="help-icon" title="{_"You see only item that you are not connected to."} {_"If these recommendations are not precise, you could try to find better tags to describe your interests. You can change your tags on your profile page."}" style="margin-bottom:-8px; float:right;"/>

	<h3>{_"The following items could be interesting for you:"}</h3>
		<div class="top-users">
			<h2>{_"Recommended Users"}</h2>
				{control homepagerecommendeduserlister:body}
			<div class="discover_new_users">
				<a href="{link User:default}" class="ajax">{_"Discover new users"}</a>
			</div>
		</div>
		<div class="top-groups">
			<h2>{_"Recommended Groups"}</h2>
				{control homepagerecommendedgrouplister:body}
			<div class="discover_new_groups">
				<a href="{link Group:default}" class="ajax">{_"Discover new groups"}</a>
			</div>
		</div>
		<div class="top-resources">
			<h2>{_"Recommended Resources"}</h2>
				{control homepagerecommendedresourcelister:body}
			<div class="discover_new_resources">
				<a href="{link Resource:default}" class="ajax">{_"Discover new resources"}</a>
			</div>
		</div>
		<div class="cleaner"></div>
	</div>

	<div id="activity">
	<div id="activity_box_home" class="activity-box">
		<input id="latest_items" type="checkbox" name="latest_items"></input>{_"Include all new users, groups and resources that you are allowed to view."}
		<div id="load-more-home-1">
		</div>
	</div>
	<script>
		$(document).ready(function(){
			$("input[name='latest_items']").change(function(){
				var latest = $(this).prop('checked')?'1':'0';
				loadActivity("#load-more-home-1", 2, latest);
			});

		});
	</script>
	</div>

	<div id="events">
		<div class="calendar-info" style="padding:1em;">
			<p><span style="background-color:#E13C20; padding:2px 5px; margin:5px; display:inline;"></span> {_"own events"}</p>
			<p><span style="background-color:#4680B3; padding:2px 5px; margin:5px; display:inline;"></span> {_"subscribed events"}</p>
		</div>
		<div id='calendar'></div>
	</div>
<script>
	$(document).ready(function() {
		$('#calendar').fullCalendar({
			contentHeight: 600,
			firstDay:1,
			ignoreTimezone: false,
			header: {
				left:   'title',
				center: '',
				right:  'today agendaDay,agendaWeek,month prev,next'
			},
			eventSources: [
			"/?do=getevents"{ifset $xml_events}{foreach $xml_events as $xml_event}{? $xml_event_data = explode(",", $xml_event)},
			{ url:"{!$xml_event_data[0]}", {if !empty($xml_event_data[1])}backgroundColor: "{!$xml_event_data[1]}", {/if}className:'google-event'}{/foreach}{/if}],
		    eventRender: function(event, element) {
        		element.qtip({
            		content: event.description
		      	});
	  		{ifset $xml_events}$('.google-event').attr('target','_blank');{/if}
		    },
       		dayClick: function(date, allDay, jsEvent, view) {
				if (confirm({_"Create a new event?"})) {
					if (allDay) {
						window.location = "/resource/create?date="+encodeURIComponent(date)+"&all_day=1"
					} else {
						window.location = "/resource/create?date="+encodeURIComponent(date)
					}
				}
			},
			eventDrop: function(event,dayDelta,minuteDelta,allDay,revertFunc, jsEvent, ui, view) {
				if (view.name != 'agendaWeek' && view.name != 'agendaDay') allDay=null;
				if (!$.post("/?do=changeevent&changed=start&resource_id=" +event.id+"&day_delta="+dayDelta+"&minute_delta="+minuteDelta+"&allday="+allDay)) revertFunc();
			},
			eventResize: function(event,dayDelta,minuteDelta,revertFunc) {
				if (!$.post("/?do=changeevent&changed=end&resource_id=" +event.id+"&day_delta="+dayDelta+"&minute_delta="+minuteDelta)) revertFunc();
			},
			buttonText: {
				today:	{_"today"},
				month:	{_"month"},
				week:	{_"week"},
				day:	{_"day"}
			},
			monthNames: [{_"January"}, {_"February"}, {_"March"}, {_"April"}, {_"May"}, {_"June"}, {_"July"},
 {_"August"}, {_"September"}, {_"October"}, {_"November"}, {_"December"}],
			monthNamesShort: [{_"Jan"}, {_"Feb"}, {_"Mar"}, {_"Apr"}, {_"May"}, {_"Jun"}, {_"Jul"}, {_"Aug"}, {_"Sep"}, {_"Oct"}, {_"Nov"}, {_"Dec"}],
			dayNames: [{_"Sunday"}, {_"Monday"}, {_"Tuesday"}, {_"Wednesday"},
 {_"Thursday"}, {_"Friday"}, {_"Saturday"}],
			dayNamesShort: [{_"Sun"}, {_"Mon"}, {_"Tue"}, {_"Wed"}, {_"Thu"}, {_"Fri"}, {_"Sat"}],
  		});
	});
</script>
{ifset $home_tabs}{foreach $home_tabs as $home_tab}{? $home_tab_data = explode(",", $home_tab)}
		<iframe id='slide_{$home_tab_data[0]}' src="" style="width:90%;height:700px;border:none;"></iframe>
{/foreach}{/if}
</div>
</div>
<script>
	$(document).ready(function() {

		$("#tab_headers").fadeIn(1200);
				
		$("#tabs").fadeIn(800).tabs({
			activate: function(event, ui) {
				if (ui.newTab.attr('id') == 'tab_events') {
					$('#calendar').fullCalendar( 'render' );
				}
				if (ui.newTab.attr('id') == 'tab_activity') {
					var latest = $("input[name='latest_items']").prop('checked')?'1':'0';
					loadActivity("#load-more-home-1", 2, latest);
				}
{ifset $home_tabs}{foreach $home_tabs as $home_tab}{? $home_tab_data = explode(",", $home_tab)}
				if (ui.newTab.attr('id') == "tab_{!$home_tab_data[0]}") {
					$("#slide_{!$home_tab_data[0]}").attr("src","{!$home_tab_data[2]}");
				}
{/foreach}{/if}
			},
			hide: 800,
			show: 800
		});

	});
</script>

<!-- BEGIN Filter for my connections -->
<div id="filter_container" style="display:none;">
	{control filter}
</div>
<script>
$(document).ready(function(){
	if ($('#filter_box_a').attr('class') == 'filter-button-off') {
		$('#frmfilter-reset').hide();
	} else {
		$('#filter-help').hide();
	}
});
</script>

<script type="text/javascript">
$(function() {
	$("#filter_box_a").fancybox({
		minWidth : 1000,
		minHeight : 550,
		closeBtn : true,
		helpers : {
			overlay : {
				css: {'background' : 'rgba(200, 200, 200, .5)'}
			},
			title : null
		},
	});
});
</script>
<!-- END Filter for my connections -->

{else}{* Users who are not logged in see "top" items. *}
<div class="wrapper-home-B">
	<div class="homepage_default_users">
		<h3>{_"Top Users"}</h3>		
		{control userHomepage:body}
	</div>
	<div class="homepage_default_groups">
		<h3>{_"Top Groups"}</h3>
		 {control groupHomepage:body}
	</div>
	<div class="homepage_default_resources">
		<h3>{_"Top Resources"}</h3>
		 {control resourceHomepage:body}
	</div>
</div>
{/if}
{/block}
