<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.2 beta
 *
 * @author http://mycitizen.org
 *
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{var load_js_css_zxcvbn => true}
{block title}{_"Change lost password"}{/block}
{block content}
<div class="wrapper-text">
	{control changelostpasswordform}
</div>

<script>
	var oldText,oldRepeat;
	$(document).ready(function(){
		$("#frmchangelostpasswordform-user_password").keyup(function(){
			var color;
			var password = $("#frmchangelostpasswordform-user_password").val();
			if (password == oldText) { return true;}
			var user_inputs = new Array();
			user_inputs.push = {$username};
			var result = zxcvbn(password, user_inputs);
			switch(result.score) {
				case 0: color = "#FF0000"; break;
				case 1: color = "#FFBF00"; break;
				case 2: color = "#FFFF00"; break;
				case 3: color = "#80FF00"; break;
				case 4: color = "#01DF01"; break;
			}
			$('#frmchangelostpasswordform-user_password').css({ "background-color":color});			
			oldText = password;
			oldRepeat = "";
		});
		$("#frmchangelostpasswordform-password_again").keyup(function(){ comparePasswords()});
		$("#frmchangelostpasswordform-user_password").keyup(function(){ comparePasswords()});
	});
	
	function comparePasswords(){
			var color;
			var again = $("#frmchangelostpasswordform-password_again").val();
			if (again == oldRepeat) { return true;}
			var password = $("#frmregisterform-user_password").val();
			if ((again.length == 0) || (password == again)) {
				color = "transparent";
			} else {
				color = "#FF0000";
			}
			$('#frmchangelostpasswordform-password_again').css({ "background-color":color});			
			oldRepeat = again;
		}
</script>
{/block}
