<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"User update"}{/block}
@{block #content}
<div class="user_edit_updateform">	
	{control updateform error}
	{control updateform begin}
	<div class="back"><a href="{plink User:default, $user_id}" title="{_"cancel and return"}" class="ajax"><b class="icon-cancel"></b></a></div>
<div class="edit-primary">
{if !isset($image_too_large) && !isset($image_props_wrong)}
	<h2>{_"Basic Information"}</h2>
{/if}
{if isset($img_src) && $img_src!=null}
	<div class="user-edit-image{if !isset($image_too_large) && !isset($image_props_wrong)} edit-image-small{/if}">
		<h3>{_"Edit your avatar"}</h3>
		<div class="images">
			<div class="image-full"><img src="data:{$mime_type};base64,{$img_src}" id="crop"/></div>
			<div class="icon-large"><p>Large icon:</p>{ifset $large_icon}{!$large_icon}{else}{_"Needs to be created."}{/if}</div>
			<div class="icon-small"><p>Small icon:</p>{ifset $icon}{!$icon}{else}{_"Needs to be created."}{/if}</div>
		</div>
		<div class="cleaner"></div>
		<div class="image-buttons">
		{if isset($image_too_large) ||  isset($image_props_wrong)}
			<div>{_"Click inside the image and select your avatar."}</div>
		{/if}

			<input type="submit" value="remove" onClick="removeAvatar({ifset $administrated_user}{$administrated_user}{else}null{/if});return false;" />
			<input type="hidden" id="x" name="x" />
			<input type="hidden" id="y" name="y" />
			<input type="hidden" id="w" name="w" />
			<input type="hidden" id="h" name="h" />
			<input type="hidden" id="factor" value="{$factor}" />
			<a href="javascript:void(0);" id="crop_button" onClick="doCrop(); return false;" class="button">{_"crop and resize"}</a>
		</div>
	</div>
{/if}
{if !isset($image_too_large) && !isset($image_props_wrong)}
	<div class="edit-wrapper">
	<table>
		<tbody>
			{foreach $control['updateform']->getControls() as $key=>$ctrl}
			{if !isset($image_too_large) && !isset($image_props_wrong)}
			<tr>
				<td>
					{$ctrl->label}
				</td>
				<td>
					{$ctrl->control}
					{ifset $ctrl->options['description']}
					{$ctrl->options['description']}
					{/if}
				</td>
			</tr>
			{/if}
			{/foreach}
			<tr>
			<td>
			</td>
			<td>{if !isset($image_too_large) && !isset($image_props_wrong)}<a href="/user/changepassword/?user_id={$user_id}" class="button">{_"Change password"}</a>{/if}
			</td>
			</tr>
		</tbody>
	</table>

	{control updateform end}
	</div>
<div class="cleaner"></div>
</div>
{/if}

{if !isset($image_too_large) && !isset($image_props_wrong)}
<div class="edit-secondary">
	<h2>{_"Additional Information"}</h2>
{/if}
<table class="edit-secondary-table">
<tr>
{if !isset($image_too_large) && !isset($image_props_wrong)}
	<td class="edit-secondary-table-td">
	<div class="user-edit-map">
		<h3>{_"Edit your location"}</h3>
    	{control mapedit}
	</div>
	</td>
{/if}

	<td class="edit-secondary-table-td">
		{if !isset($image_too_large) && !isset($image_props_wrong)}
		<h3>{_"Add or remove tags"}</h3><img src="{$baseUri}/images/help.png" class="help-icon" title="{_"Add the tags one by one."}" style="float:right;"/>
		{/if}
	   {control tagform begin}
		{snippet tagHandle}
			<table id="rule_tail_container" class="newSelect">
				{if !isset($image_too_large) && !isset($image_props_wrong)}
				{ifset $user_tags}
				 {foreach $user_tags as $key=>$tag_name}
					<tr>
						<td>
							{foreach $tag_name->getPath() as $tag}
								<span>{? echo _t_tags($tag)}</span>
								{if !$iterator->isLast()}
									<div style="width=0;height:0;border-left: 5px solid #BCB6AA;border-top: 5px solid transparent; border-bottom: 5px solid transparent;display:inline-block;"></div>
								{/if}
							{/foreach}
						</td> 
						<td>
							<input type="submit" value="X" onClick="removeTag_User({$key},{ifset $administrated_user}{$administrated_user}{else}null{/if});return false;" />
						</td>
					</tr>
				{/foreach}
				{/if}
				{/if}
			</table>
	   {/snippet}
		{if !isset($image_too_large) && !isset($image_props_wrong)}
			{!$control['tagform']['add_tag']->control}
		{/if}
		{control tagform end}
<script>
	$(document).ready(function(){
		$('a#tag_select_button').addClass('button');
	});
</script>
	</td>
</tr>
</table>
{if !isset($image_too_large) && !isset($image_props_wrong)}
	<div class="cleaner"></div>
</div>
{/if}
<script>
    jQuery(function($) {
        $('#crop').Jcrop({
        	minSize: [{!$min_size_x},{!$min_size_y}],
        	aspectRatio: 4/5,
        	onChange: enableCrop,
			onSelect: enableCrop
        });
    });
</script>
{/block}
