<?php
/**
 * mycitizen.net - Open source social networking for civil society
 *
 * @version 0.3 beta
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{var $robots => "noindex,nofollow"}
{block title}{_"User signin"}{/block}
{block content}
<div class="wrapper-text">
	{ifset $logged}
		<a href="{link Homepage:logout}" class="button">{_"Sign out"}</a>
	{else}
		{ifset $sign_in_disabled}
		<div class="login-box">
			<h3>{_"Sign in is disabled. Please try again later."}</h3>
		</div>
		{/if}
		{control loginform begin}
			<table>
				<tr><td colspan="2">
					<h4>{_"Already have an account? Sign in below."}</h4>
				</td></tr>
				<tr>
            		<td>{$control['loginform']['user_login']->label}</td>
        			<td>{$control['loginform']['user_login']->control}</td>
        		</tr>
				<tr>
					<td>{$control['loginform']['user_password']->label}</td>
                    <td>{$control['loginform']['user_password']->control}</td>
				</tr>
				<tr>
					<td>{$control['loginform']['remember_me']->label}</td>
                    <td>{$control['loginform']['remember_me']->control}</td>
				</tr>
				<tr>
					<td></td>
					<td>
						<a href="{link User:lostpassword}">{_"Click here if you forgot your password."}</a>
					</td>
				</tr>
				<tr>
					<td></td>
					<td>{$control['loginform']['signin']->control}</td>
				</tr>
				<tr><td colspan="2">
					{_"If you are new here, please "} <a href="{link User:register}">{_"sign up"}</a>.
				</td></tr>
			</table>
		{control loginform end}
	{/if}
</div>
{/block}
