<?php
/**
 * mycitizen.net - Social networking for civil society
 *
 *
 * @author http://mycitizen.org
 * @copyright  Copyright (c) 2013, 2014 Burma Center Prague (http://www.burma-center.org)
 * @link http://mycitizen.net
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3
 *
 * @package mycitizen.net
 */
?>
{block title}{_"Your messages"}{/block}
{block content}
<div class="wrapper-text">
	<div id="message_top_anchor"></div>
	{control messageform begin}
	<div class="about">
		<h1>{_"Send a message to a friend"}</h1>
		<div class="message-to">
			{$control['messageform']['friend_id']->control}
		</div>
	</div>
	<div class="detail-right">
		{ifset $nofriends}
			{_"You have no friends yet. You can start sending messages only after someone has accepted your friendship request."}
		{else}
		<div class="message-text">
			{$control['messageform']['message_text']->control}
		</div>
		<div class="message-send">
		 	{$control['messageform']['send']->control}
		</div>
		{/if}
	</div>
	{control messageform end}


	<div class="detail-right-bottom">
		<h2>{_"Your messages"}</h2>
		<div class="filter-block">
			<input type="text" class="text" name="name" id="search_name" value="" onkeyup="textChanged();" placeholder="{_"Filter by name"}"/>
			<a href="javascript:void(0);" id="clear_button" class="button" name="clear" >{_"Clear"}</a>
		</div>
		<div class="reload-messages" style="float:right;">
			<b onclick="javascript:location.reload();" class="icon-reload" title="{_"Reload"}" style="cursor:pointer;"></b>
			<a href="#settings_container" id="settings_box" title="{_"Notification Settings"}"><b class="icon-setting"></b></a>
		</div>

			<div id="settings_container" style="display:none;">
				<h2>{_"Notification Settings"}</h2>
				{control notificationsform}
			</div>
			<script type="text/javascript">
			$(function() {
				$("#settings_box").fancybox({
					minWidth : 400,
					minHeight : 200,
					closeBtn : true,
					helpers : {
						overlay : {
							css: {'background' : 'rgba(200, 200, 200, .5)'}
						},
						title : null
					},
				});
			});
			</script>
	
		<div class="user-messages">
			{control messagelisteruser}
		</div>
	</div>

	<script>
		$(document).ready(function() {
			if ($('#frmfilter-trash-0').is(':checked')) $('#empty-trash').hide();
			if ($('#frmfilter-trash-1').is(':checked')) $('#empty-trash').hide();

			$('#clear_button').click(function(){
				$('#search_name').val('');
				showAll();
			});
		});
		
		var text='';
		var search='';
		
		function textChanged() {
			search = $('#search_name').val();
			if (search == text) {
				return false;
			}
			search = search.trim();
			filter();
			text = search;
		}
		
		$.extend($.expr[":"], {
			"containsNC": function(elem, i, match, array) {
				return (elem.textContent || elem.innerText || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
			}
		});

		function showAll() {
			$('.chat-author').parent().parent().parent().slideDown(600);
		}
		
		function filter() {
			if (search.length<text.length) {
				$('.chat-author').parent().parent().parent().slideDown(600);
				$('.chat-author:not(:containsNC('+search+'))').parent().parent().parent().slideUp(600);
			}
			else if (search!='') {
				$('.chat-author:not(:containsNC('+search+'))').parent().parent().parent().slideUp(600);
			}
		}

	</script>

	<script>
		$(document).ready(function(){
			$('[id^=reply_]').click(function(){
				var id = parseInt($(this).attr('id').substr(-5,5));
				var elements = document.getElementsByName( 'message_text' );
				var instance_name = elements[0].getAttribute( 'id' );
				var quote = $('[id$='+id+'_text]').html();
				quote = quote.replace(/(<([^>]+[^(blockquote)])>)/ig,"");
				var author_name = $('[id$='+id+'_author]').html().trim();
				var author_id = $('[id$='+id+'_author]').attr('rel');
				var date = $('[id$='+id+'_date]').html();
				var quote_shortened = quote.substr(0,300);
				if (quote_shortened != quote ) { quote_shortened += '...'; }
				$('#frmmessageform-friend_id').val(author_id);
				var reply = '<br/><br/><blockquote id="quoting_0000'+id+'"><b><span style="color:#999;">{!_"Quote"}: '+author_name+'</span></b>, <span style="color:#333;"><b>'+date+'</b></span>:<br />'+quote_shortened+'</blockquote><br/>';
				content = reply;
				//editor.setContent(content);
				CKEDITOR.instances[instance_name].insertHtml(content);
				$('html, body').animate({
					scrollTop: $("#message_top_anchor").offset().top
				}, 2000);
				CKEDITOR.instances[instance_name].focus();
			});
		
			$('blockquote').click(function(){
				var id = parseInt($(this).attr('id').substr(-5,5));
				$('html, body').animate({
					scrollTop: $("#chat_message_"+id).offset().top
				}, 'normal');
			});
		
			$('blockquote').mouseover(function(){
				var id = parseInt($(this).attr('id').substr(-5,5));
				$("#chat_message_"+id).css({ "border-left":"solid 4px #E08E1B", "padding-left":"20px"}); 
				if ($("#chat_message_"+id).css("border-left")) {
					$(this).css('cursor','pointer');
				};
			});

			$('blockquote').mouseout(function(){
				var id = parseInt($(this).attr('id').substr(-5,5));
				$("#chat_message_"+id).css({ "border-left":"inherit", "padding-left":"0"});
			});
		
		});
	</script>
<script>
	$(document).ready(function() {
		CKEDITOR.replace( 'message_text', {
			height: '200px',
			width: '740px',
			filebrowserUploadUrl: '/?do=upload',
			filebrowserBrowseUrl: '/widget/browse/',
			allowedContent: 'p strong em; a[!href]; del ins; ul ol li; img(left,right)[!src,alt,width,height]; blockquote[id]',
			toolbarGroups: [
				{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
				{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ]},
				{ name: 'links'},
				{ name: 'insert'},
				{ name: 'styles'},
				{ name: 'colors'}
			],
			extraPlugins: 'smiley'
		});
	});
</script>
</div>
{/block}

